// Generated by @lagless/codegen. Do not edit manually.
import { AbstractInputProvider, ECSConfig } from '@lagless/core';
import { IECSSystemConstructor, ISignalConstructor } from '@lagless/core';
import { PhysicsRunner2d, PhysicsConfig2d, RapierModule2d } from '@lagless/physics2d';
import { CollisionLayers } from '@lagless/physics-shared';

import { MapTestCore } from './MapTest.core.js';

export class MapTestRunner extends PhysicsRunner2d {
  constructor(
    Config: ECSConfig,
    InputProviderInstance: AbstractInputProvider,
    Systems: Array<IECSSystemConstructor>,
    Signals: Array<ISignalConstructor> = [],
    rapier: RapierModule2d,
    physicsConfig?: PhysicsConfig2d,
    collisionLayers?: CollisionLayers,
    extraRegistrations?: Array<[unknown, unknown]>
  ) {
    super(
      Config,
      InputProviderInstance,
      Systems,
      Signals,
      MapTestCore,
      rapier,
      physicsConfig,
      collisionLayers,
      extraRegistrations
    );
  }
}
