// Generated by @lagless/codegen. Do not edit manually.
import { ECSDeps } from '@lagless/core';

import { Transform2d } from './Transform2d.js';
import { PhysicsRefs } from './PhysicsRefs.js';
import { PlayerBody } from './PlayerBody.js';

import { PlayerResource } from './PlayerResource.js';
import { PlayerFilter } from './PlayerFilter.js';
import { PhysicsRefsFilter } from './PhysicsRefsFilter.js';
import { PlayerJoined } from './PlayerJoined.js';
import { PlayerLeft } from './PlayerLeft.js';
import { MoveInput } from './MoveInput.js';

export const MapTestCore: ECSDeps = {
  components: [Transform2d, PhysicsRefs, PlayerBody],
  singletons: [],
  playerResources: [PlayerResource],
  filters: [PlayerFilter, PhysicsRefsFilter],
  inputs: [PlayerJoined, PlayerLeft, MoveInput],
};
