// Generated by @lagless/codegen. Do not edit manually.
import { AbstractFilter, IComponentConstructor } from '@lagless/core';
import { PhysicsRefs } from './PhysicsRefs.js';
import { Transform2d } from './Transform2d.js';

export class PhysicsRefsFilter extends AbstractFilter {
  public static readonly include: Array<IComponentConstructor> = [PhysicsRefs, Transform2d];
  public static readonly exclude: Array<IComponentConstructor> = [];

  public readonly includeMask: number[] = [3];
  public readonly excludeMask: number[] = [0];
}

Object.defineProperty(PhysicsRefsFilter, 'name', { value: 'PhysicsRefsFilter' });
