// Generated by @lagless/codegen. Do not edit manually.
import { AbstractFilter, IComponentConstructor } from '@lagless/core';
import { Transform2d } from './Transform2d.js';
import { PhysicsRefs } from './PhysicsRefs.js';
import { PlayerBody } from './PlayerBody.js';

export class PlayerFilter extends AbstractFilter {
  public static readonly include: Array<IComponentConstructor> = [Transform2d, PhysicsRefs, PlayerBody];
  public static readonly exclude: Array<IComponentConstructor> = [];

  public readonly includeMask: number[] = [7];
  public readonly excludeMask: number[] = [0];
}

Object.defineProperty(PlayerFilter, 'name', { value: 'PlayerFilter' });
