packages:
  - 'apps/*'
  - 'libs/*'
  - 'tools/*'
  - 'circle-race/*'
  - 'libs/api/*'
  - 'circle-sumo/*'
  - 'sync-test/*'
  - 'roblox-like/*'
  - '!tools/create/templates/**'
autoInstallPeers: true
strictPeerDependencies: false
