export default [
  'libs/binary',
  'libs/math',
  'libs/misc',
  'libs/core',
  'libs/net-wire',
  'libs/relay-server',
  'libs/relay-client',
  'libs/matchmaking',
  'libs/physics-shared',
  'libs/physics3d',
  'libs/physics2d',
  'libs/2d-map/2d-map-generator',
  'libs/2d-map/2d-map-renderer',
  '2d-map-test/2d-map-test-simulation',
  'libs/desync-diagnostics',
  'libs/react',
];
