// Generated by @lagless/codegen. Do not edit manually.
import { AbstractFilter, IComponentConstructor } from '@lagless/core';
import { Transform2d } from './Transform2d.js';
import { Ball } from './Ball.js';

export class BallFilter extends AbstractFilter {
  public static readonly include: Array<IComponentConstructor> = [Transform2d, Ball];
  public static readonly exclude: Array<IComponentConstructor> = [];

  public readonly includeMask: number = 5;
  public readonly excludeMask: number = 0;
}

Object.defineProperty(BallFilter, 'name', { value: 'BallFilter' });
