// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class Ball {
  public static readonly ID = 4;
  public static readonly schema = {
    ownerSlot: Uint8Array,

    active: Uint8Array,

    radius: Float32Array,
  };

  public readonly unsafe = {} as {
    ownerSlot: Uint8Array;

    active: Uint8Array;

    radius: Float32Array;
  };

  private _cursorIndex = 0;
  private readonly _cursor: {
    readonly entity: number;

    ownerSlot: number;

    active: number;

    radius: number;
  };

  public getCursor(index: number) {
    this._cursorIndex = index;
    return this._cursor;
  }

  constructor(maxEntities: number, buffer: ArrayBuffer, memTracker: MemoryTracker) {
    for (const [fieldName, TypedArrayConstructor] of Object.entries(Ball.schema)) {
      const typedArray = new TypedArrayConstructor(buffer, memTracker.ptr, maxEntities);
      this.unsafe[fieldName as keyof typeof Ball.schema] = typedArray as Ball['unsafe'][keyof Ball['unsafe']];
      memTracker.add(typedArray.byteLength);
    }

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this._cursor = {
      get entity(): number {
        return self._cursorIndex;
      },

      get ownerSlot(): number {
        return self.unsafe.ownerSlot[self._cursorIndex];
      },

      set ownerSlot(value: number) {
        self.unsafe.ownerSlot[self._cursorIndex] = value;
      },

      get active(): number {
        return self.unsafe.active[self._cursorIndex];
      },

      set active(value: number) {
        self.unsafe.active[self._cursorIndex] = value;
      },

      get radius(): number {
        return self.unsafe.radius[self._cursorIndex];
      },

      set radius(value: number) {
        self.unsafe.radius[self._cursorIndex] = value;
      },
    };
  }

  public static calculateSize(maxEntities: number, memTracker: MemoryTracker): void {
    for (const [, TypedArrayConstructor] of Object.entries(this.schema)) {
      memTracker.add(maxEntities * TypedArrayConstructor.BYTES_PER_ELEMENT);
    }
  }
}

Object.defineProperty(Ball, 'name', { value: 'Ball' });
