// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class Goal {
  public static readonly ID = 16;
  public static readonly schema = {
    ownerSlot: Uint8Array,

    halfWidth: Float32Array,
  };

  public readonly unsafe = {} as {
    ownerSlot: Uint8Array;

    halfWidth: Float32Array;
  };

  private _cursorIndex = 0;
  private readonly _cursor: {
    readonly entity: number;

    ownerSlot: number;

    halfWidth: number;
  };

  public getCursor(index: number) {
    this._cursorIndex = index;
    return this._cursor;
  }

  constructor(maxEntities: number, buffer: ArrayBuffer, memTracker: MemoryTracker) {
    for (const [fieldName, TypedArrayConstructor] of Object.entries(Goal.schema)) {
      const typedArray = new TypedArrayConstructor(buffer, memTracker.ptr, maxEntities);
      this.unsafe[fieldName as keyof typeof Goal.schema] = typedArray as Goal['unsafe'][keyof Goal['unsafe']];
      memTracker.add(typedArray.byteLength);
    }

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this._cursor = {
      get entity(): number {
        return self._cursorIndex;
      },

      get ownerSlot(): number {
        return self.unsafe.ownerSlot[self._cursorIndex];
      },

      set ownerSlot(value: number) {
        self.unsafe.ownerSlot[self._cursorIndex] = value;
      },

      get halfWidth(): number {
        return self.unsafe.halfWidth[self._cursorIndex];
      },

      set halfWidth(value: number) {
        self.unsafe.halfWidth[self._cursorIndex] = value;
      },
    };
  }

  public static calculateSize(maxEntities: number, memTracker: MemoryTracker): void {
    for (const [, TypedArrayConstructor] of Object.entries(this.schema)) {
      memTracker.add(maxEntities * TypedArrayConstructor.BYTES_PER_ELEMENT);
    }
  }
}

Object.defineProperty(Goal, 'name', { value: 'Goal' });
