// Generated by @lagless/codegen. Do not edit manually.
import { AbstractFilter, IComponentConstructor } from '@lagless/core';
import { Transform2d } from './Transform2d.js';
import { Goal } from './Goal.js';

export class GoalFilter extends AbstractFilter {
  public static readonly include: Array<IComponentConstructor> = [Transform2d, Goal];
  public static readonly exclude: Array<IComponentConstructor> = [];

  public readonly includeMask: number = 17;
  public readonly excludeMask: number = 0;
}

Object.defineProperty(GoalFilter, 'name', { value: 'GoalFilter' });
