// Generated by @lagless/codegen. Do not edit manually.
import { InputRegistry } from '@lagless/core';

import { PlayerJoined } from './PlayerJoined.js';
import { PlayerLeft } from './PlayerLeft.js';
import { Shoot } from './Shoot.js';
import { ReportHash } from './ReportHash.js';

export const GravityPongInputRegistry = new InputRegistry([PlayerJoined, PlayerLeft, Shoot, ReportHash]);
