// Generated by @lagless/codegen. Do not edit manually.
import { ECSDeps } from '@lagless/core';

import { Transform2d } from './Transform2d.js';
import { Velocity2d } from './Velocity2d.js';
import { Ball } from './Ball.js';
import { GravitySource } from './GravitySource.js';
import { Goal } from './Goal.js';
import { MatchState } from './MatchState.js';
import { PlayerResource } from './PlayerResource.js';
import { BallFilter } from './BallFilter.js';
import { GravitySourceFilter } from './GravitySourceFilter.js';
import { GoalFilter } from './GoalFilter.js';
import { MovingFilter } from './MovingFilter.js';
import { PlayerJoined } from './PlayerJoined.js';
import { PlayerLeft } from './PlayerLeft.js';
import { Shoot } from './Shoot.js';
import { ReportHash } from './ReportHash.js';

export const GravityPongCore: ECSDeps = {
  components: [Transform2d, Velocity2d, Ball, GravitySource, Goal],
  singletons: [MatchState],
  playerResources: [PlayerResource],
  filters: [BallFilter, GravitySourceFilter, GoalFilter, MovingFilter],
  inputs: [PlayerJoined, PlayerLeft, Shoot, ReportHash],
};
