// Generated by @lagless/codegen. Do not edit manually.
import { AbstractInputProvider, ECSConfig, ECSRunner } from '@lagless/core';
import { IECSSystemConstructor, ISignalConstructor } from '@lagless/core';

import { GravityPongCore } from './GravityPong.core.js';

export class GravityPongRunner extends ECSRunner {
  constructor(
    Config: ECSConfig,
    InputProviderInstance: AbstractInputProvider,
    Systems: Array<IECSSystemConstructor>,
    Signals: Array<ISignalConstructor> = []
  ) {
    super(Config, InputProviderInstance, Systems, Signals, GravityPongCore);
  }
}
