// Generated by @lagless/codegen. Do not edit manually.
import { AbstractFilter, IComponentConstructor } from '@lagless/core';
import { Transform2d } from './Transform2d.js';
import { GravitySource } from './GravitySource.js';

export class GravitySourceFilter extends AbstractFilter {
  public static readonly include: Array<IComponentConstructor> = [Transform2d, GravitySource];
  public static readonly exclude: Array<IComponentConstructor> = [];

  public readonly includeMask: number = 9;
  public readonly excludeMask: number = 0;
}

Object.defineProperty(GravitySourceFilter, 'name', { value: 'GravitySourceFilter' });
