// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class GravitySource {
  public static readonly ID = 8;
  public static readonly schema = {
    mass: Float32Array,

    radius: Float32Array,

    isBlackHole: Uint8Array,
  };

  public readonly unsafe = {} as {
    mass: Float32Array;

    radius: Float32Array;

    isBlackHole: Uint8Array;
  };

  private _cursorIndex = 0;
  private readonly _cursor: {
    readonly entity: number;

    mass: number;

    radius: number;

    isBlackHole: number;
  };

  public getCursor(index: number) {
    this._cursorIndex = index;
    return this._cursor;
  }

  constructor(maxEntities: number, buffer: ArrayBuffer, memTracker: MemoryTracker) {
    for (const [fieldName, TypedArrayConstructor] of Object.entries(GravitySource.schema)) {
      const typedArray = new TypedArrayConstructor(buffer, memTracker.ptr, maxEntities);
      this.unsafe[fieldName as keyof typeof GravitySource.schema] =
        typedArray as GravitySource['unsafe'][keyof GravitySource['unsafe']];
      memTracker.add(typedArray.byteLength);
    }

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this._cursor = {
      get entity(): number {
        return self._cursorIndex;
      },

      get mass(): number {
        return self.unsafe.mass[self._cursorIndex];
      },

      set mass(value: number) {
        self.unsafe.mass[self._cursorIndex] = value;
      },

      get radius(): number {
        return self.unsafe.radius[self._cursorIndex];
      },

      set radius(value: number) {
        self.unsafe.radius[self._cursorIndex] = value;
      },

      get isBlackHole(): number {
        return self.unsafe.isBlackHole[self._cursorIndex];
      },

      set isBlackHole(value: number) {
        self.unsafe.isBlackHole[self._cursorIndex] = value;
      },
    };
  }

  public static calculateSize(maxEntities: number, memTracker: MemoryTracker): void {
    for (const [, TypedArrayConstructor] of Object.entries(this.schema)) {
      memTracker.add(maxEntities * TypedArrayConstructor.BYTES_PER_ELEMENT);
    }
  }
}

Object.defineProperty(GravitySource, 'name', { value: 'GravitySource' });
