// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class MatchState {
  public static readonly schema = {
    phase: Uint8Array,

    scoreP0: Uint8Array,

    scoreP1: Uint8Array,

    phaseStartTick: Uint32Array,

    roundNumber: Uint8Array,

    ballsResolved: Uint8Array,
  };

  public readonly unsafe = {} as {
    phase: Uint8Array;

    scoreP0: Uint8Array;

    scoreP1: Uint8Array;

    phaseStartTick: Uint32Array;

    roundNumber: Uint8Array;

    ballsResolved: Uint8Array;
  };

  public readonly safe: {
    phase: number;

    scoreP0: number;

    scoreP1: number;

    phaseStartTick: number;

    roundNumber: number;

    ballsResolved: number;
  };

  constructor(buffer: ArrayBuffer, memTracker: MemoryTracker) {
    // phase
    this.unsafe['phase'] = new Uint8Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);

    // scoreP0
    this.unsafe['scoreP0'] = new Uint8Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);

    // scoreP1
    this.unsafe['scoreP1'] = new Uint8Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);

    // phaseStartTick
    this.unsafe['phaseStartTick'] = new Uint32Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // roundNumber
    this.unsafe['roundNumber'] = new Uint8Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);

    // ballsResolved
    this.unsafe['ballsResolved'] = new Uint8Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this.safe = {
      get phase() {
        return self.unsafe['phase'][0];
      },
      set phase(value: number) {
        self.unsafe['phase'][0] = value;
      },

      get scoreP0() {
        return self.unsafe['scoreP0'][0];
      },
      set scoreP0(value: number) {
        self.unsafe['scoreP0'][0] = value;
      },

      get scoreP1() {
        return self.unsafe['scoreP1'][0];
      },
      set scoreP1(value: number) {
        self.unsafe['scoreP1'][0] = value;
      },

      get phaseStartTick() {
        return self.unsafe['phaseStartTick'][0];
      },
      set phaseStartTick(value: number) {
        self.unsafe['phaseStartTick'][0] = value;
      },

      get roundNumber() {
        return self.unsafe['roundNumber'][0];
      },
      set roundNumber(value: number) {
        self.unsafe['roundNumber'][0] = value;
      },

      get ballsResolved() {
        return self.unsafe['ballsResolved'][0];
      },
      set ballsResolved(value: number) {
        self.unsafe['ballsResolved'][0] = value;
      },
    };
  }

  public static calculateSize(memTracker: MemoryTracker): void {
    // phase
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);

    // scoreP0
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);

    // scoreP1
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);

    // phaseStartTick
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // roundNumber
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);

    // ballsResolved
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);
  }
}

Object.defineProperty(MatchState, 'name', { value: 'MatchState' });
