// Generated by @lagless/codegen. Do not edit manually.
import { FieldType } from '@lagless/binary';

export class Shoot {
  public static readonly id = 3;
  public readonly id = 3;

  // 4 + 4 = 8;
  public readonly byteLength = 8;

  public readonly fields = [
    { name: 'angle', type: FieldType.Float32, isArray: false, byteLength: 4 },

    { name: 'power', type: FieldType.Float32, isArray: false, byteLength: 4 },
  ] as const;

  public readonly schema!: {
    angle: number;

    power: number;
  };
}
