// Generated by @lagless/codegen. Do not edit manually.
import { InputRegistry } from '@lagless/core';

import { PlayerJoined } from './PlayerJoined.js';
import { PlayerLeft } from './PlayerLeft.js';
import { Move } from './Move.js';

export const CircleRaceSimulationInputRegistry = new InputRegistry([PlayerJoined, PlayerLeft, Move]);
