// Generated by @lagless/codegen. Do not edit manually.
import { AbstractInputProvider, ECSConfig, ECSRunner } from '@lagless/core';
import { IECSSystemConstructor } from '@lagless/core';

import { CircleRaceSimulationCore } from './CircleRaceSimulation.core.js';

export class CircleRaceSimulationRunner extends ECSRunner {
  constructor(Config: ECSConfig, InputProviderInstance: AbstractInputProvider, Systems: Array<IECSSystemConstructor>) {
    super(Config, InputProviderInstance, Systems, CircleRaceSimulationCore);
  }
}
