// Generated by @lagless/codegen. Do not edit manually.
import { ECSDeps } from '@lagless/core';

import { Transform2d } from './Transform2d.js';
import { Velocity2d } from './Velocity2d.js';

import { PlayerResource } from './PlayerResource.js';
import { Transform2dFilter } from './Transform2dFilter.js';
import { MovableFilter } from './MovableFilter.js';
import { PlayerJoined } from './PlayerJoined.js';
import { PlayerLeft } from './PlayerLeft.js';
import { Move } from './Move.js';

export const CircleRaceSimulationCore: ECSDeps = {
  components: [Transform2d, Velocity2d],
  singletons: [],
  playerResources: [PlayerResource],
  filters: [Transform2dFilter, MovableFilter],
  inputs: [PlayerJoined, PlayerLeft, Move],
};
