// Generated by @lagless/codegen. Do not edit manually.
import { AbstractFilter, IComponentConstructor } from '@lagless/core';
import { Transform2d } from './Transform2d.js';
import { Velocity2d } from './Velocity2d.js';

export class MovableFilter extends AbstractFilter {
  public static readonly include: Array<IComponentConstructor> = [Transform2d, Velocity2d];
  public static readonly exclude: Array<IComponentConstructor> = [];

  public readonly includeMask: number = 3;
  public readonly excludeMask: number = 0;
}

Object.defineProperty(MovableFilter, 'name', { value: 'MovableFilter' });
