// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class PlayerResource {
  public static readonly schema = {
    id: Uint8Array,

    entity: Uint32Array,
  };

  public readonly unsafe = {} as {
    id: Uint8Array;

    entity: Uint32Array;
  };

  public readonly safe: {
    readonly id: Uint8Array;

    entity: number;
  };

  constructor(buffer: ArrayBuffer, memTracker: MemoryTracker) {
    // id
    this.unsafe['id'] = new Uint8Array(buffer, memTracker.ptr, 16);
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 16);

    // entity
    this.unsafe['entity'] = new Uint32Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this.safe = {
      get id() {
        return self.unsafe['id'];
      },

      get entity() {
        return self.unsafe['entity'][0];
      },
      set entity(value: number) {
        self.unsafe['entity'][0] = value;
      },
    };
  }

  public static calculateSize(memTracker: MemoryTracker): void {
    // id
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 16);

    // entity
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);
  }
}

Object.defineProperty(PlayerResource, 'name', { value: 'PlayerResource' });
