// Generated by @lagless/codegen. Do not edit manually.
import { FieldType } from '@lagless/binary';

export class PlayerLeft {
  public static readonly id = 2;
  public readonly id = 2;

  // 1 = 1;
  public readonly byteLength = 1;

  public readonly fields = [{ name: 'reason', type: FieldType.Uint8, isArray: false, byteLength: 1 }] as const;

  public readonly schema!: {
    reason: number;
  };
}
