// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class Velocity2d {
  public static readonly ID = 2;
  public static readonly schema = {
    velocityX: Float32Array,

    velocityY: Float32Array,
  };

  public readonly unsafe = {} as {
    velocityX: Float32Array;

    velocityY: Float32Array;
  };

  private _cursorIndex = 0;
  private readonly _cursor: {
    readonly entity: number;

    readonly velocityX: number;

    readonly velocityY: number;
  };

  public getCursor(index: number) {
    this._cursorIndex = index;
    return this._cursor;
  }

  constructor(maxEntities: number, buffer: ArrayBuffer, memTracker: MemoryTracker) {
    for (const [fieldName, TypedArrayConstructor] of Object.entries(Velocity2d.schema)) {
      const typedArray = new TypedArrayConstructor(buffer, memTracker.ptr, maxEntities);
      this.unsafe[fieldName as keyof typeof Velocity2d.schema] =
        typedArray as Velocity2d['unsafe'][keyof Velocity2d['unsafe']];
      memTracker.add(typedArray.byteLength);
    }

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this._cursor = {
      get entity(): number {
        return self._cursorIndex;
      },

      get velocityX(): number {
        return self.unsafe.velocityX[self._cursorIndex];
      },

      set velocityX(value: number) {
        self.unsafe.velocityX[self._cursorIndex] = value;
      },

      get velocityY(): number {
        return self.unsafe.velocityY[self._cursorIndex];
      },

      set velocityY(value: number) {
        self.unsafe.velocityY[self._cursorIndex] = value;
      },
    };
  }

  public static calculateSize(maxEntities: number, memTracker: MemoryTracker): void {
    for (const [, TypedArrayConstructor] of Object.entries(this.schema)) {
      memTracker.add(maxEntities * TypedArrayConstructor.BYTES_PER_ELEMENT);
    }
  }
}

Object.defineProperty(Velocity2d, 'name', { value: 'Velocity2d' });
