// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class GameState {
  public static readonly schema = {
    score: Int32Array,

    level: Int32Array,
  };

  public readonly unsafe = {} as {
    score: Int32Array;

    level: Int32Array;
  };

  constructor(buffer: ArrayBuffer, memTracker: MemoryTracker) {
    // score
    this.unsafe['score'] = new Int32Array(buffer, memTracker.ptr, 1);
    memTracker.add(Int32Array.BYTES_PER_ELEMENT * 1);

    // level
    this.unsafe['level'] = new Int32Array(buffer, memTracker.ptr, 1);
    memTracker.add(Int32Array.BYTES_PER_ELEMENT * 1);
  }

  public static calculateSize(memTracker: MemoryTracker): void {
    // score
    memTracker.add(Int32Array.BYTES_PER_ELEMENT * 1);

    // level
    memTracker.add(Int32Array.BYTES_PER_ELEMENT * 1);
  }
}

Object.defineProperty(GameState, 'name', { value: 'GameState' });
