// Generated by @lagless/codegen. Do not edit manually.
import { FieldType } from '@lagless/binary';

export class MoveMultipleInput {
  public static readonly id = 2;
  public readonly id = 2;

  // 4 + 4 + 128 + 4 = 140;
  public readonly byteLength = 140;

  public readonly fields = [
    { name: 'direction', type: FieldType.Float32, isArray: false, byteLength: 4 },

    { name: 'speed', type: FieldType.Float32, isArray: false, byteLength: 4 },

    { name: 'entities', type: FieldType.Uint32, isArray: true, arrayLength: 32, byteLength: 128 },

    { name: 'entitiesLength', type: FieldType.Uint32, isArray: false, byteLength: 4 },
  ] as const;

  public readonly schema!: {
    direction: number;

    speed: number;

    entities: Uint32Array;

    entitiesLength: number;
  };
}
