// Generated by @lagless/codegen. Do not edit manually.
import { AbstractFilter, IComponentConstructor } from '@lagless/core';
import { Transform2d } from './Transform2d.js';
import { Projectile } from './Projectile.js';

export class MovingProjectiles extends AbstractFilter {
  public static readonly include: Array<IComponentConstructor> = [Transform2d, Projectile];
  public static readonly exclude: Array<IComponentConstructor> = [];

  public readonly includeMask: number = 3;
  public readonly excludeMask: number = 0;
}

Object.defineProperty(MovingProjectiles, 'name', { value: 'MovingProjectiles' });
