// Generated by @lagless/codegen. Do not edit manually.
import { InputRegistry } from '@lagless/core';

import { MoveInput } from './MoveInput.js';
import { MoveMultipleInput } from './MoveMultipleInput.js';

export const TestbedInputRegistry = new InputRegistry([MoveInput, MoveMultipleInput]);
