// Generated by @lagless/codegen. Do not edit manually.
import { AbstractInputProvider, ECSConfig, ECSRunner } from '@lagless/core';
import { IECSSystemConstructor } from '@lagless/core';

import { TestbedCore } from './Testbed.core.js';

export class TestbedRunner extends ECSRunner {
  constructor(Config: ECSConfig, InputProviderInstance: AbstractInputProvider, Systems: Array<IECSSystemConstructor>) {
    super(Config, InputProviderInstance, Systems, TestbedCore);
  }
}
