// Generated by @lagless/codegen. Do not edit manually.
import { ECSDeps } from '@lagless/types';

import { Transform2d } from './Transform2d.js';
import { PhysicsRefs } from './PhysicsRefs.js';

export const CrazyBallsSimulationECSCore: ECSDeps = {
  components: [Transform2d, PhysicsRefs],
  singletons: [],
  playerResources: [],
  filters: [],
  inputs: [],
};
