import { ECSSchema, FieldDefinition } from '@lagless/core';
import { generateFromTemplate as processTemplate, FileOperations } from './template-engine.js';
import { FieldTypeReverse, getTypeSizeBytes, typedArrayConstructors, typeToArrayConstructor } from '@lagless/binary';
import { SimulationType } from './parser.js';

export interface GenerateCodeOptions {
  schema: ECSSchema;
  projectName: string;
  outputDir: string;
  templateDir: string;
  fileOperations: FileOperations;
  simulationType?: SimulationType;
}

export function generateBarrelFileContent(schema: ECSSchema, projectName: string): string {
  let content = '// Generated by @lagless/codegen. Do not edit manually.\n\n';

  // Export components
  schema.components.forEach((component) => {
    content += `export * from './${component.name}.js';\n`;
  });

  // Export singletons
  schema.singletons.forEach((singleton) => {
    content += `export * from './${singleton.name}.js';\n`;
  });

  // Export player resources
  schema.playerResources.forEach((playerResource) => {
    content += `export * from './${playerResource.name}.js';\n`;
  });

  // Export filters
  schema.filters.forEach((filter) => {
    content += `export * from './${filter.name}.js';\n`;
  });

  // Export inputs
  schema.inputs.forEach((input) => {
    content += `export * from './${input.name}.js';\n`;
  });

  // Export input registry
  content += `export * from './${projectName}InputRegistry.js';\n`;

  // Export core
  content += `export * from './${projectName}.core.js';\n`;

  // Export runner
  content += `export * from './${projectName}.runner.js';\n`;

  return content;
}

export async function generateCode(options: GenerateCodeOptions): Promise<void> {
  const { schema, projectName, outputDir, templateDir, fileOperations } = options;
  const { writeFile, joinPath, exists } = fileOperations;

  // Ensure output directory exists
  if (!exists(outputDir)) {
    writeFile(joinPath(outputDir, '.gitkeep'), '');
  }

  // Generate component classes
  for (const component of schema.components) {
    await processTemplate({
      templateDir: joinPath(templateDir, 'component'),
      outputDir,
      data: {
        ...component,
        component,
        projectName,
        typeToArrayConstructor,
        getFieldByteSize: (field: FieldDefinition) => {
          const baseSize = getTypeSizeBytes(field.type);
          return field.isArray ? baseSize * field.arrayLength! : baseSize;
        },
      },
      fileOperations,
    });
  }

  // Generate singleton classes
  for (const singleton of schema.singletons) {
    await processTemplate({
      templateDir: joinPath(templateDir, 'singleton'),
      outputDir,
      data: {
        ...singleton,
        singleton,
        projectName,
        typeToArrayConstructor,
      },
      fileOperations,
    });
  }

  // Generate playerResource classes
  for (const playerResource of schema.playerResources) {
    await processTemplate({
      templateDir: joinPath(templateDir, 'playerResource'),
      outputDir,
      data: {
        ...playerResource,
        playerResource,
        projectName,
        typeToArrayConstructor,
      },
      fileOperations,
    });
  }

  // Determine mask word count from component count
  const maskWords = Math.max(1, Math.ceil(schema.components.length / 32));

  // Generate Filter classes (masks are number[] with one element per Uint32 word)
  for (const filter of schema.filters) {
    const componentsImports = [...filter.include, ...filter.exclude].map((c) => c.name);

    const includeMaskWords = new Array<number>(maskWords).fill(0);
    for (const component of filter.include) {
      const w = component.id >>> 5;
      includeMaskWords[w] |= 1 << (component.id & 31);
    }

    const excludeMaskWords = new Array<number>(maskWords).fill(0);
    for (const component of filter.exclude) {
      const w = component.id >>> 5;
      excludeMaskWords[w] |= 1 << (component.id & 31);
    }

    await processTemplate({
      templateDir: joinPath(templateDir, 'filter'),
      outputDir,
      data: {
        filter,
        includeMaskWords,
        excludeMaskWords,
        componentsImports,
        name: filter.name,
        projectName,
      },
      fileOperations,
    });
  }

  // Generate Input classes
  for (const input of schema.inputs) {
    await processTemplate({
      templateDir: joinPath(templateDir, 'input'),
      outputDir,
      data: {
        ...input,
        input,
        projectName,
        FieldTypeReverse,
        typedArrayConstructors,
      },
      fileOperations,
    });
  }

  // Generate input registry
  await processTemplate({
    templateDir: joinPath(templateDir, 'input-registry'),
    outputDir,
    data: {
      projectName,
      inputs: schema.inputs,
      schema,
    },
    fileOperations,
  });

  // Generate ECSCore class
  await processTemplate({
    templateDir: joinPath(templateDir, 'core'),
    outputDir,
    data: {
      projectName,
      schema,
    },
    fileOperations,
  });

  // Generate Runner class (template varies by simulationType)
  const simulationType = options.simulationType ?? 'raw';
  const runnerTemplateDir =
    simulationType === 'physics3d' ? 'runner-physics3d' : simulationType === 'physics2d' ? 'runner-physics2d' : 'runner';

  await processTemplate({
    templateDir: joinPath(templateDir, runnerTemplateDir),
    outputDir,
    data: {
      projectName,
      schema,
    },
    fileOperations,
  });

  // Generate barrel file
  const barrelContent = generateBarrelFileContent(schema, projectName);
  writeFile(joinPath(outputDir, 'index.ts'), barrelContent);
}
