// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class Collectible {
  public static readonly ID = 3;
  public static readonly schema = {
    value: Uint16Array,

    spawnTick: Uint32Array,
  };

  public readonly unsafe = {} as {
    value: Uint16Array;

    spawnTick: Uint32Array;
  };

  private _cursorIndex = 0;
  private readonly _cursor: {
    readonly entity: number;

    value: number;

    spawnTick: number;
  };

  public getCursor(index: number) {
    this._cursorIndex = index;
    return this._cursor;
  }

  constructor(maxEntities: number, buffer: ArrayBuffer, memTracker: MemoryTracker) {
    for (const [fieldName, TypedArrayConstructor] of Object.entries(Collectible.schema)) {
      const typedArray = new TypedArrayConstructor(buffer, memTracker.ptr, maxEntities);
      this.unsafe[fieldName as keyof typeof Collectible.schema] =
        typedArray as Collectible['unsafe'][keyof Collectible['unsafe']];
      memTracker.add(typedArray.byteLength);
    }

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this._cursor = {
      get entity(): number {
        return self._cursorIndex;
      },

      get value(): number {
        return self.unsafe.value[self._cursorIndex];
      },

      set value(value: number) {
        self.unsafe.value[self._cursorIndex] = value;
      },

      get spawnTick(): number {
        return self.unsafe.spawnTick[self._cursorIndex];
      },

      set spawnTick(value: number) {
        self.unsafe.spawnTick[self._cursorIndex] = value;
      },
    };
  }

  public static calculateSize(maxEntities: number, memTracker: MemoryTracker): void {
    for (const [, TypedArrayConstructor] of Object.entries(this.schema)) {
      memTracker.add(maxEntities * TypedArrayConstructor.BYTES_PER_ELEMENT);
    }
  }
}

Object.defineProperty(Collectible, 'name', { value: 'Collectible' });
