// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class GameState {
  public static readonly schema = {
    nextSpawnTick: Uint32Array,

    totalCollected: Uint32Array,

    gamePhase: Uint8Array,
  };

  public readonly unsafe = {} as {
    nextSpawnTick: Uint32Array;

    totalCollected: Uint32Array;

    gamePhase: Uint8Array;
  };

  public readonly safe: {
    nextSpawnTick: number;

    totalCollected: number;

    gamePhase: number;
  };

  constructor(buffer: ArrayBuffer, memTracker: MemoryTracker) {
    // nextSpawnTick
    this.unsafe['nextSpawnTick'] = new Uint32Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // totalCollected
    this.unsafe['totalCollected'] = new Uint32Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // gamePhase
    this.unsafe['gamePhase'] = new Uint8Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this.safe = {
      get nextSpawnTick() {
        return self.unsafe['nextSpawnTick'][0];
      },
      set nextSpawnTick(value: number) {
        self.unsafe['nextSpawnTick'][0] = value;
      },

      get totalCollected() {
        return self.unsafe['totalCollected'][0];
      },
      set totalCollected(value: number) {
        self.unsafe['totalCollected'][0] = value;
      },

      get gamePhase() {
        return self.unsafe['gamePhase'][0];
      },
      set gamePhase(value: number) {
        self.unsafe['gamePhase'][0] = value;
      },
    };
  }

  public static calculateSize(memTracker: MemoryTracker): void {
    // nextSpawnTick
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // totalCollected
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // gamePhase
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);
  }
}

Object.defineProperty(GameState, 'name', { value: 'GameState' });
