// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class PlayerBody {
  public static readonly ID = 2;
  public static readonly schema = {
    playerSlot: Uint8Array,

    radius: Float32Array,
  };

  public readonly unsafe = {} as {
    playerSlot: Uint8Array;

    radius: Float32Array;
  };

  private _cursorIndex = 0;
  private readonly _cursor: {
    readonly entity: number;

    playerSlot: number;

    radius: number;
  };

  public getCursor(index: number) {
    this._cursorIndex = index;
    return this._cursor;
  }

  constructor(maxEntities: number, buffer: ArrayBuffer, memTracker: MemoryTracker) {
    for (const [fieldName, TypedArrayConstructor] of Object.entries(PlayerBody.schema)) {
      const typedArray = new TypedArrayConstructor(buffer, memTracker.ptr, maxEntities);
      this.unsafe[fieldName as keyof typeof PlayerBody.schema] =
        typedArray as PlayerBody['unsafe'][keyof PlayerBody['unsafe']];
      memTracker.add(typedArray.byteLength);
    }

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this._cursor = {
      get entity(): number {
        return self._cursorIndex;
      },

      get playerSlot(): number {
        return self.unsafe.playerSlot[self._cursorIndex];
      },

      set playerSlot(value: number) {
        self.unsafe.playerSlot[self._cursorIndex] = value;
      },

      get radius(): number {
        return self.unsafe.radius[self._cursorIndex];
      },

      set radius(value: number) {
        self.unsafe.radius[self._cursorIndex] = value;
      },
    };
  }

  public static calculateSize(maxEntities: number, memTracker: MemoryTracker): void {
    for (const [, TypedArrayConstructor] of Object.entries(this.schema)) {
      memTracker.add(maxEntities * TypedArrayConstructor.BYTES_PER_ELEMENT);
    }
  }
}

Object.defineProperty(PlayerBody, 'name', { value: 'PlayerBody' });
