// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class PlayerResource {
  public static readonly schema = {
    id: Uint8Array,

    entity: Uint32Array,

    connected: Uint8Array,

    score: Uint32Array,

    collectCount: Uint16Array,

    lastReportedHash: Uint32Array,

    lastReportedHashTick: Uint32Array,

    hashMismatchCount: Uint16Array,
  };

  public readonly unsafe = {} as {
    id: Uint8Array;

    entity: Uint32Array;

    connected: Uint8Array;

    score: Uint32Array;

    collectCount: Uint16Array;

    lastReportedHash: Uint32Array;

    lastReportedHashTick: Uint32Array;

    hashMismatchCount: Uint16Array;
  };

  public readonly safe: {
    readonly id: Uint8Array;

    entity: number;

    connected: number;

    score: number;

    collectCount: number;

    lastReportedHash: number;

    lastReportedHashTick: number;

    hashMismatchCount: number;
  };

  constructor(buffer: ArrayBuffer, memTracker: MemoryTracker) {
    // id
    this.unsafe['id'] = new Uint8Array(buffer, memTracker.ptr, 16);
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 16);

    // entity
    this.unsafe['entity'] = new Uint32Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // connected
    this.unsafe['connected'] = new Uint8Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);

    // score
    this.unsafe['score'] = new Uint32Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // collectCount
    this.unsafe['collectCount'] = new Uint16Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint16Array.BYTES_PER_ELEMENT * 1);

    // lastReportedHash
    this.unsafe['lastReportedHash'] = new Uint32Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // lastReportedHashTick
    this.unsafe['lastReportedHashTick'] = new Uint32Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // hashMismatchCount
    this.unsafe['hashMismatchCount'] = new Uint16Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint16Array.BYTES_PER_ELEMENT * 1);

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this.safe = {
      get id() {
        return self.unsafe['id'];
      },

      get entity() {
        return self.unsafe['entity'][0];
      },
      set entity(value: number) {
        self.unsafe['entity'][0] = value;
      },

      get connected() {
        return self.unsafe['connected'][0];
      },
      set connected(value: number) {
        self.unsafe['connected'][0] = value;
      },

      get score() {
        return self.unsafe['score'][0];
      },
      set score(value: number) {
        self.unsafe['score'][0] = value;
      },

      get collectCount() {
        return self.unsafe['collectCount'][0];
      },
      set collectCount(value: number) {
        self.unsafe['collectCount'][0] = value;
      },

      get lastReportedHash() {
        return self.unsafe['lastReportedHash'][0];
      },
      set lastReportedHash(value: number) {
        self.unsafe['lastReportedHash'][0] = value;
      },

      get lastReportedHashTick() {
        return self.unsafe['lastReportedHashTick'][0];
      },
      set lastReportedHashTick(value: number) {
        self.unsafe['lastReportedHashTick'][0] = value;
      },

      get hashMismatchCount() {
        return self.unsafe['hashMismatchCount'][0];
      },
      set hashMismatchCount(value: number) {
        self.unsafe['hashMismatchCount'][0] = value;
      },
    };
  }

  public static calculateSize(memTracker: MemoryTracker): void {
    // id
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 16);

    // entity
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // connected
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);

    // score
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // collectCount
    memTracker.add(Uint16Array.BYTES_PER_ELEMENT * 1);

    // lastReportedHash
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // lastReportedHashTick
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // hashMismatchCount
    memTracker.add(Uint16Array.BYTES_PER_ELEMENT * 1);
  }
}

Object.defineProperty(PlayerResource, 'name', { value: 'PlayerResource' });
