// Generated by @lagless/codegen. Do not edit manually.
import { ECSDeps } from '@lagless/core';

import { Transform2d } from './Transform2d.js';
import { Velocity2d } from './Velocity2d.js';
import { PlayerBody } from './PlayerBody.js';
import { Collectible } from './Collectible.js';
import { GameState } from './GameState.js';
import { PlayerResource } from './PlayerResource.js';
import { PlayerFilter } from './PlayerFilter.js';
import { CollectibleFilter } from './CollectibleFilter.js';
import { MovingFilter } from './MovingFilter.js';
import { PlayerJoined } from './PlayerJoined.js';
import { PlayerLeft } from './PlayerLeft.js';
import { MoveInput } from './MoveInput.js';
import { ReportHash } from './ReportHash.js';

export const SyncTestCore: ECSDeps = {
  components: [Transform2d, Velocity2d, PlayerBody, Collectible],
  singletons: [GameState],
  playerResources: [PlayerResource],
  filters: [PlayerFilter, CollectibleFilter, MovingFilter],
  inputs: [PlayerJoined, PlayerLeft, MoveInput, ReportHash],
};
