// Generated by @lagless/codegen. Do not edit manually.
import { InputRegistry } from '@lagless/core';

import { PlayerJoined } from './PlayerJoined.js';
import { PlayerLeft } from './PlayerLeft.js';
import { MoveInput } from './MoveInput.js';

export const SyncTestInputRegistry = new InputRegistry([PlayerJoined, PlayerLeft, MoveInput]);
