// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class Bot {
  public static readonly ID = 7;
  public static readonly schema = {
    lastPanicTick: Uint32Array,

    nextDecisionTick: Uint32Array,

    aggressiveness: Float32Array,
  };

  public readonly unsafe = {} as {
    lastPanicTick: Uint32Array;

    nextDecisionTick: Uint32Array;

    aggressiveness: Float32Array;
  };

  private _cursorIndex = 0;
  private readonly _cursor: {
    readonly entity: number;

    lastPanicTick: number;

    nextDecisionTick: number;

    aggressiveness: number;
  };

  public getCursor(index: number) {
    this._cursorIndex = index;
    return this._cursor;
  }

  constructor(maxEntities: number, buffer: ArrayBuffer, memTracker: MemoryTracker) {
    this.unsafe.lastPanicTick = new Uint32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.lastPanicTick.byteLength);

    this.unsafe.nextDecisionTick = new Uint32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.nextDecisionTick.byteLength);

    this.unsafe.aggressiveness = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.aggressiveness.byteLength);

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this._cursor = {
      get entity(): number {
        return self._cursorIndex;
      },

      get lastPanicTick(): number {
        return self.unsafe.lastPanicTick[self._cursorIndex];
      },

      set lastPanicTick(value: number) {
        self.unsafe.lastPanicTick[self._cursorIndex] = value;
      },

      get nextDecisionTick(): number {
        return self.unsafe.nextDecisionTick[self._cursorIndex];
      },

      set nextDecisionTick(value: number) {
        self.unsafe.nextDecisionTick[self._cursorIndex] = value;
      },

      get aggressiveness(): number {
        return self.unsafe.aggressiveness[self._cursorIndex];
      },

      set aggressiveness(value: number) {
        self.unsafe.aggressiveness[self._cursorIndex] = value;
      },
    };
  }

  public static calculateSize(maxEntities: number, memTracker: MemoryTracker): void {
    for (const [, TypedArrayConstructor] of Object.entries(this.schema)) {
      memTracker.add(maxEntities * TypedArrayConstructor.BYTES_PER_ELEMENT);
    }
  }
}

Object.defineProperty(Bot, 'name', { value: 'Bot' });
