// Generated by @lagless/codegen. Do not edit manually.
import { AbstractFilter, IComponentConstructor } from '@lagless/core';
import { Bot } from './Bot.js';
import { Transform2d } from './Transform2d.js';
import { CircleBody } from './CircleBody.js';

export class BotFilter extends AbstractFilter {
  public static readonly include: Array<IComponentConstructor> = [Bot, Transform2d, CircleBody];
  public static readonly exclude: Array<IComponentConstructor> = [];

  public readonly includeMask: number[] = [138];
  public readonly excludeMask: number[] = [0];
}

Object.defineProperty(BotFilter, 'name', { value: 'BotFilter' });
