// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class CircleBody {
  public static readonly ID = 3;
  public static readonly schema = {
    playerSlot: Uint8Array,

    radius: Float32Array,

    mass: Float32Array,

    restitution: Float32Array,

    linearDamping: Float32Array,

    angularDamping: Float32Array,
  };

  public readonly unsafe = {} as {
    playerSlot: Uint8Array;

    radius: Float32Array;

    mass: Float32Array;

    restitution: Float32Array;

    linearDamping: Float32Array;

    angularDamping: Float32Array;
  };

  private _cursorIndex = 0;
  private readonly _cursor: {
    readonly entity: number;

    playerSlot: number;

    radius: number;

    mass: number;

    restitution: number;

    linearDamping: number;

    angularDamping: number;
  };

  public getCursor(index: number) {
    this._cursorIndex = index;
    return this._cursor;
  }

  constructor(maxEntities: number, buffer: ArrayBuffer, memTracker: MemoryTracker) {
    this.unsafe.playerSlot = new Uint8Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.playerSlot.byteLength);

    this.unsafe.radius = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.radius.byteLength);

    this.unsafe.mass = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.mass.byteLength);

    this.unsafe.restitution = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.restitution.byteLength);

    this.unsafe.linearDamping = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.linearDamping.byteLength);

    this.unsafe.angularDamping = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.angularDamping.byteLength);

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this._cursor = {
      get entity(): number {
        return self._cursorIndex;
      },

      get playerSlot(): number {
        return self.unsafe.playerSlot[self._cursorIndex];
      },

      set playerSlot(value: number) {
        self.unsafe.playerSlot[self._cursorIndex] = value;
      },

      get radius(): number {
        return self.unsafe.radius[self._cursorIndex];
      },

      set radius(value: number) {
        self.unsafe.radius[self._cursorIndex] = value;
      },

      get mass(): number {
        return self.unsafe.mass[self._cursorIndex];
      },

      set mass(value: number) {
        self.unsafe.mass[self._cursorIndex] = value;
      },

      get restitution(): number {
        return self.unsafe.restitution[self._cursorIndex];
      },

      set restitution(value: number) {
        self.unsafe.restitution[self._cursorIndex] = value;
      },

      get linearDamping(): number {
        return self.unsafe.linearDamping[self._cursorIndex];
      },

      set linearDamping(value: number) {
        self.unsafe.linearDamping[self._cursorIndex] = value;
      },

      get angularDamping(): number {
        return self.unsafe.angularDamping[self._cursorIndex];
      },

      set angularDamping(value: number) {
        self.unsafe.angularDamping[self._cursorIndex] = value;
      },
    };
  }

  public static calculateSize(maxEntities: number, memTracker: MemoryTracker): void {
    for (const [, TypedArrayConstructor] of Object.entries(this.schema)) {
      memTracker.add(maxEntities * TypedArrayConstructor.BYTES_PER_ELEMENT);
    }
  }
}

Object.defineProperty(CircleBody, 'name', { value: 'CircleBody' });
