// Generated by @lagless/codegen. Do not edit manually.
import { ECSDeps } from '@lagless/core';

import { Skin } from './Skin.js';
import { Transform2d } from './Transform2d.js';
import { Velocity2d } from './Velocity2d.js';
import { CircleBody } from './CircleBody.js';
import { PendingImpulse } from './PendingImpulse.js';
import { LastHit } from './LastHit.js';
import { LastAssist } from './LastAssist.js';
import { Bot } from './Bot.js';
import { GameState } from './GameState.js';
import { PlayerResource } from './PlayerResource.js';
import { Transform2dFilter } from './Transform2dFilter.js';
import { PendingImpulseFilter } from './PendingImpulseFilter.js';
import { Velocity2dFilter } from './Velocity2dFilter.js';
import { DampingFilter } from './DampingFilter.js';
import { SumoCharacterFilter } from './SumoCharacterFilter.js';
import { BotFilter } from './BotFilter.js';
import { PlayerJoined } from './PlayerJoined.js';
import { PlayerLeft } from './PlayerLeft.js';
import { Move } from './Move.js';
import { LookAt } from './LookAt.js';

export const CircleSumoCore: ECSDeps = {
  components: [Skin, Transform2d, Velocity2d, CircleBody, PendingImpulse, LastHit, LastAssist, Bot],
  singletons: [GameState],
  playerResources: [PlayerResource],
  filters: [Transform2dFilter, PendingImpulseFilter, Velocity2dFilter, DampingFilter, SumoCharacterFilter, BotFilter],
  inputs: [PlayerJoined, PlayerLeft, Move, LookAt],
};
