// Generated by @lagless/codegen. Do not edit manually.
import { AbstractFilter, IComponentConstructor } from '@lagless/core';
import { Velocity2d } from './Velocity2d.js';
import { CircleBody } from './CircleBody.js';

export class DampingFilter extends AbstractFilter {
  public static readonly include: Array<IComponentConstructor> = [Velocity2d, CircleBody];
  public static readonly exclude: Array<IComponentConstructor> = [];

  public readonly includeMask: number = 6;
  public readonly excludeMask: number = 0;
}

Object.defineProperty(DampingFilter, 'name', { value: 'DampingFilter' });
