// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class GameState {
  public static readonly schema = {
    playerFinishedCount: Uint8Array,

    startedAtTick: Uint32Array,

    finishedAtTick: Uint32Array,
  };

  public readonly unsafe = {} as {
    playerFinishedCount: Uint8Array;

    startedAtTick: Uint32Array;

    finishedAtTick: Uint32Array;
  };

  public readonly safe: {
    playerFinishedCount: number;

    startedAtTick: number;

    finishedAtTick: number;
  };

  constructor(buffer: ArrayBuffer, memTracker: MemoryTracker) {
    // playerFinishedCount
    this.unsafe['playerFinishedCount'] = new Uint8Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);

    // startedAtTick
    this.unsafe['startedAtTick'] = new Uint32Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // finishedAtTick
    this.unsafe['finishedAtTick'] = new Uint32Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this.safe = {
      get playerFinishedCount() {
        return self.unsafe['playerFinishedCount'][0];
      },
      set playerFinishedCount(value: number) {
        self.unsafe['playerFinishedCount'][0] = value;
      },

      get startedAtTick() {
        return self.unsafe['startedAtTick'][0];
      },
      set startedAtTick(value: number) {
        self.unsafe['startedAtTick'][0] = value;
      },

      get finishedAtTick() {
        return self.unsafe['finishedAtTick'][0];
      },
      set finishedAtTick(value: number) {
        self.unsafe['finishedAtTick'][0] = value;
      },
    };
  }

  public static calculateSize(memTracker: MemoryTracker): void {
    // playerFinishedCount
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);

    // startedAtTick
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // finishedAtTick
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);
  }
}

Object.defineProperty(GameState, 'name', { value: 'GameState' });
