// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class GameState {
  public static readonly schema = {
    finishedAtTick: Int32Array,
  };

  public readonly unsafe = {} as {
    finishedAtTick: Int32Array;
  };

  public readonly safe: {
    finishedAtTick: number;
  };

  constructor(buffer: ArrayBuffer, memTracker: MemoryTracker) {
    // finishedAtTick
    this.unsafe['finishedAtTick'] = new Int32Array(buffer, memTracker.ptr, 1);
    memTracker.add(Int32Array.BYTES_PER_ELEMENT * 1);

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this.safe = {
      get finishedAtTick() {
        return self.unsafe['finishedAtTick'][0];
      },
      set finishedAtTick(value: number) {
        self.unsafe['finishedAtTick'][0] = value;
      },
    };
  }

  public static calculateSize(memTracker: MemoryTracker): void {
    // finishedAtTick
    memTracker.add(Int32Array.BYTES_PER_ELEMENT * 1);
  }
}

Object.defineProperty(GameState, 'name', { value: 'GameState' });
