// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class LastAssist {
  public static readonly ID = 32;
  public static readonly schema = {
    hasAssister: Uint8Array,

    assisterEntity: Uint32Array,

    atTick: Uint32Array,
  };

  public readonly unsafe = {} as {
    hasAssister: Uint8Array;

    assisterEntity: Uint32Array;

    atTick: Uint32Array;
  };

  private _cursorIndex = 0;
  private readonly _cursor: {
    readonly entity: number;

    hasAssister: number;

    assisterEntity: number;

    atTick: number;
  };

  public getCursor(index: number) {
    this._cursorIndex = index;
    return this._cursor;
  }

  constructor(maxEntities: number, buffer: ArrayBuffer, memTracker: MemoryTracker) {
    for (const [fieldName, TypedArrayConstructor] of Object.entries(LastAssist.schema)) {
      const typedArray = new TypedArrayConstructor(buffer, memTracker.ptr, maxEntities);
      this.unsafe[fieldName as keyof typeof LastAssist.schema] =
        typedArray as LastAssist['unsafe'][keyof LastAssist['unsafe']];
      memTracker.add(typedArray.byteLength);
    }

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this._cursor = {
      get entity(): number {
        return self._cursorIndex;
      },

      get hasAssister(): number {
        return self.unsafe.hasAssister[self._cursorIndex];
      },

      set hasAssister(value: number) {
        self.unsafe.hasAssister[self._cursorIndex] = value;
      },

      get assisterEntity(): number {
        return self.unsafe.assisterEntity[self._cursorIndex];
      },

      set assisterEntity(value: number) {
        self.unsafe.assisterEntity[self._cursorIndex] = value;
      },

      get atTick(): number {
        return self.unsafe.atTick[self._cursorIndex];
      },

      set atTick(value: number) {
        self.unsafe.atTick[self._cursorIndex] = value;
      },
    };
  }

  public static calculateSize(maxEntities: number, memTracker: MemoryTracker): void {
    for (const [, TypedArrayConstructor] of Object.entries(this.schema)) {
      memTracker.add(maxEntities * TypedArrayConstructor.BYTES_PER_ELEMENT);
    }
  }
}

Object.defineProperty(LastAssist, 'name', { value: 'LastAssist' });
