// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class LastHit {
  public static readonly ID = 5;
  public static readonly schema = {
    hasAttacker: Uint8Array,

    attackerEntity: Uint32Array,

    atTick: Uint32Array,

    impulse: Float32Array,
  };

  public readonly unsafe = {} as {
    hasAttacker: Uint8Array;

    attackerEntity: Uint32Array;

    atTick: Uint32Array;

    impulse: Float32Array;
  };

  private _cursorIndex = 0;
  private readonly _cursor: {
    readonly entity: number;

    hasAttacker: number;

    attackerEntity: number;

    atTick: number;

    impulse: number;
  };

  public getCursor(index: number) {
    this._cursorIndex = index;
    return this._cursor;
  }

  constructor(maxEntities: number, buffer: ArrayBuffer, memTracker: MemoryTracker) {
    this.unsafe.hasAttacker = new Uint8Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.hasAttacker.byteLength);

    this.unsafe.attackerEntity = new Uint32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.attackerEntity.byteLength);

    this.unsafe.atTick = new Uint32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.atTick.byteLength);

    this.unsafe.impulse = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.impulse.byteLength);

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this._cursor = {
      get entity(): number {
        return self._cursorIndex;
      },

      get hasAttacker(): number {
        return self.unsafe.hasAttacker[self._cursorIndex];
      },

      set hasAttacker(value: number) {
        self.unsafe.hasAttacker[self._cursorIndex] = value;
      },

      get attackerEntity(): number {
        return self.unsafe.attackerEntity[self._cursorIndex];
      },

      set attackerEntity(value: number) {
        self.unsafe.attackerEntity[self._cursorIndex] = value;
      },

      get atTick(): number {
        return self.unsafe.atTick[self._cursorIndex];
      },

      set atTick(value: number) {
        self.unsafe.atTick[self._cursorIndex] = value;
      },

      get impulse(): number {
        return self.unsafe.impulse[self._cursorIndex];
      },

      set impulse(value: number) {
        self.unsafe.impulse[self._cursorIndex] = value;
      },
    };
  }

  public static calculateSize(maxEntities: number, memTracker: MemoryTracker): void {
    for (const [, TypedArrayConstructor] of Object.entries(this.schema)) {
      memTracker.add(maxEntities * TypedArrayConstructor.BYTES_PER_ELEMENT);
    }
  }
}

Object.defineProperty(LastHit, 'name', { value: 'LastHit' });
