// Generated by @lagless/codegen. Do not edit manually.
import { FieldType } from '@lagless/binary';

export class LookAt {
  public static readonly id = 4;
  public readonly id = 4;

  // 4 = 4;
  public readonly byteLength = 4;

  public readonly fields = [{ name: 'direction', type: FieldType.Float32, isArray: false, byteLength: 4 }] as const;

  public readonly schema!: {
    direction: number;
  };
}
