// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class PendingImpulse {
  public static readonly ID = 4;
  public static readonly schema = {
    impulseX: Float32Array,

    impulseY: Float32Array,
  };

  public readonly unsafe = {} as {
    impulseX: Float32Array;

    impulseY: Float32Array;
  };

  private _cursorIndex = 0;
  private readonly _cursor: {
    readonly entity: number;

    impulseX: number;

    impulseY: number;
  };

  public getCursor(index: number) {
    this._cursorIndex = index;
    return this._cursor;
  }

  constructor(maxEntities: number, buffer: ArrayBuffer, memTracker: MemoryTracker) {
    for (const [fieldName, TypedArrayConstructor] of Object.entries(PendingImpulse.schema)) {
      const typedArray = new TypedArrayConstructor(buffer, memTracker.ptr, maxEntities);
      this.unsafe[fieldName as keyof typeof PendingImpulse.schema] =
        typedArray as PendingImpulse['unsafe'][keyof PendingImpulse['unsafe']];
      memTracker.add(typedArray.byteLength);
    }

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this._cursor = {
      get entity(): number {
        return self._cursorIndex;
      },

      get impulseX(): number {
        return self.unsafe.impulseX[self._cursorIndex];
      },

      set impulseX(value: number) {
        self.unsafe.impulseX[self._cursorIndex] = value;
      },

      get impulseY(): number {
        return self.unsafe.impulseY[self._cursorIndex];
      },

      set impulseY(value: number) {
        self.unsafe.impulseY[self._cursorIndex] = value;
      },
    };
  }

  public static calculateSize(maxEntities: number, memTracker: MemoryTracker): void {
    for (const [, TypedArrayConstructor] of Object.entries(this.schema)) {
      memTracker.add(maxEntities * TypedArrayConstructor.BYTES_PER_ELEMENT);
    }
  }
}

Object.defineProperty(PendingImpulse, 'name', { value: 'PendingImpulse' });
