// Generated by @lagless/codegen. Do not edit manually.
import { AbstractFilter, IComponentConstructor } from '@lagless/core';
import { PendingImpulse } from './PendingImpulse.js';
import { Velocity2d } from './Velocity2d.js';
import { CircleBody } from './CircleBody.js';

export class PendingImpulseFilter extends AbstractFilter {
  public static readonly include: Array<IComponentConstructor> = [PendingImpulse, Velocity2d, CircleBody];
  public static readonly exclude: Array<IComponentConstructor> = [];

  public readonly includeMask: number = 14;
  public readonly excludeMask: number = 0;
}

Object.defineProperty(PendingImpulseFilter, 'name', { value: 'PendingImpulseFilter' });
