// Generated by @lagless/codegen. Do not edit manually.
import { FieldType } from '@lagless/binary';

export class PlayerJoined {
  public static readonly id = 1;
  public readonly id = 1;

  // 1 + 16 + 2 + 4 = 23;
  public readonly byteLength = 23;

  public readonly fields = [
    { name: 'slot', type: FieldType.Uint8, isArray: false, byteLength: 1 },

    { name: 'playerId', type: FieldType.Uint8, isArray: true, arrayLength: 16, byteLength: 16 },

    { name: 'skinId', type: FieldType.Uint16, isArray: false, byteLength: 2 },

    { name: 'mmr', type: FieldType.Uint32, isArray: false, byteLength: 4 },
  ] as const;

  public readonly schema!: {
    slot: number;

    playerId: Uint8Array;

    skinId: number;

    mmr: number;
  };
}
