// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class PlayerResource {
  public static readonly schema = {
    id: Uint8Array,

    mmr: Uint32Array,

    entity: Uint32Array,

    connected: Uint8Array,

    initialRotation: Float32Array,

    finishedAtTick: Uint32Array,

    positionInTop: Uint8Array,

    kills: Uint16Array,

    assists: Uint16Array,

    mmrChange: Int32Array,

    wasInDangerZoneTimes: Uint16Array,

    isInDangerZone: Uint8Array,
  };

  public readonly unsafe = {} as {
    id: Uint8Array;

    mmr: Uint32Array;

    entity: Uint32Array;

    connected: Uint8Array;

    initialRotation: Float32Array;

    finishedAtTick: Uint32Array;

    positionInTop: Uint8Array;

    kills: Uint16Array;

    assists: Uint16Array;

    mmrChange: Int32Array;

    wasInDangerZoneTimes: Uint16Array;

    isInDangerZone: Uint8Array;
  };

  public readonly safe: {
    readonly id: Uint8Array;

    mmr: number;

    entity: number;

    connected: number;

    initialRotation: number;

    finishedAtTick: number;

    positionInTop: number;

    kills: number;

    assists: number;

    mmrChange: number;

    wasInDangerZoneTimes: number;

    isInDangerZone: number;
  };

  constructor(buffer: ArrayBuffer, memTracker: MemoryTracker) {
    // id
    this.unsafe['id'] = new Uint8Array(buffer, memTracker.ptr, 16);
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 16);

    // mmr
    this.unsafe['mmr'] = new Uint32Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // entity
    this.unsafe['entity'] = new Uint32Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // connected
    this.unsafe['connected'] = new Uint8Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);

    // initialRotation
    this.unsafe['initialRotation'] = new Float32Array(buffer, memTracker.ptr, 1);
    memTracker.add(Float32Array.BYTES_PER_ELEMENT * 1);

    // finishedAtTick
    this.unsafe['finishedAtTick'] = new Uint32Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // positionInTop
    this.unsafe['positionInTop'] = new Uint8Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);

    // kills
    this.unsafe['kills'] = new Uint16Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint16Array.BYTES_PER_ELEMENT * 1);

    // assists
    this.unsafe['assists'] = new Uint16Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint16Array.BYTES_PER_ELEMENT * 1);

    // mmrChange
    this.unsafe['mmrChange'] = new Int32Array(buffer, memTracker.ptr, 1);
    memTracker.add(Int32Array.BYTES_PER_ELEMENT * 1);

    // wasInDangerZoneTimes
    this.unsafe['wasInDangerZoneTimes'] = new Uint16Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint16Array.BYTES_PER_ELEMENT * 1);

    // isInDangerZone
    this.unsafe['isInDangerZone'] = new Uint8Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this.safe = {
      get id() {
        return self.unsafe['id'];
      },

      get mmr() {
        return self.unsafe['mmr'][0];
      },
      set mmr(value: number) {
        self.unsafe['mmr'][0] = value;
      },

      get entity() {
        return self.unsafe['entity'][0];
      },
      set entity(value: number) {
        self.unsafe['entity'][0] = value;
      },

      get connected() {
        return self.unsafe['connected'][0];
      },
      set connected(value: number) {
        self.unsafe['connected'][0] = value;
      },

      get initialRotation() {
        return self.unsafe['initialRotation'][0];
      },
      set initialRotation(value: number) {
        self.unsafe['initialRotation'][0] = value;
      },

      get finishedAtTick() {
        return self.unsafe['finishedAtTick'][0];
      },
      set finishedAtTick(value: number) {
        self.unsafe['finishedAtTick'][0] = value;
      },

      get positionInTop() {
        return self.unsafe['positionInTop'][0];
      },
      set positionInTop(value: number) {
        self.unsafe['positionInTop'][0] = value;
      },

      get kills() {
        return self.unsafe['kills'][0];
      },
      set kills(value: number) {
        self.unsafe['kills'][0] = value;
      },

      get assists() {
        return self.unsafe['assists'][0];
      },
      set assists(value: number) {
        self.unsafe['assists'][0] = value;
      },

      get mmrChange() {
        return self.unsafe['mmrChange'][0];
      },
      set mmrChange(value: number) {
        self.unsafe['mmrChange'][0] = value;
      },

      get wasInDangerZoneTimes() {
        return self.unsafe['wasInDangerZoneTimes'][0];
      },
      set wasInDangerZoneTimes(value: number) {
        self.unsafe['wasInDangerZoneTimes'][0] = value;
      },

      get isInDangerZone() {
        return self.unsafe['isInDangerZone'][0];
      },
      set isInDangerZone(value: number) {
        self.unsafe['isInDangerZone'][0] = value;
      },
    };
  }

  public static calculateSize(memTracker: MemoryTracker): void {
    // id
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 16);

    // mmr
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // entity
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // connected
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);

    // initialRotation
    memTracker.add(Float32Array.BYTES_PER_ELEMENT * 1);

    // finishedAtTick
    memTracker.add(Uint32Array.BYTES_PER_ELEMENT * 1);

    // positionInTop
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);

    // kills
    memTracker.add(Uint16Array.BYTES_PER_ELEMENT * 1);

    // assists
    memTracker.add(Uint16Array.BYTES_PER_ELEMENT * 1);

    // mmrChange
    memTracker.add(Int32Array.BYTES_PER_ELEMENT * 1);

    // wasInDangerZoneTimes
    memTracker.add(Uint16Array.BYTES_PER_ELEMENT * 1);

    // isInDangerZone
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);
  }
}

Object.defineProperty(PlayerResource, 'name', { value: 'PlayerResource' });
