// Generated by @lagless/codegen. Do not edit manually.
import { FieldType } from '@lagless/binary';

export class PlayerJoined {
  public static readonly id = 1;
  public readonly id = 1;

  // 16 = 16;
  public readonly byteLength = 16;

  public readonly fields = [
    { name: 'playerId', type: FieldType.Uint8, isArray: true, arrayLength: 16, byteLength: 16 },
  ] as const;

  public readonly schema!: {
    playerId: Uint8Array;
  };
}
