// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class Skin {
  public static readonly ID = 0;
  public static readonly schema = {
    skinId: Uint16Array,
  };

  public readonly unsafe = {} as {
    skinId: Uint16Array;
  };

  private _cursorIndex = 0;
  private readonly _cursor: {
    readonly entity: number;

    skinId: number;
  };

  public getCursor(index: number) {
    this._cursorIndex = index;
    return this._cursor;
  }

  constructor(maxEntities: number, buffer: ArrayBuffer, memTracker: MemoryTracker) {
    for (const [fieldName, TypedArrayConstructor] of Object.entries(Skin.schema)) {
      const typedArray = new TypedArrayConstructor(buffer, memTracker.ptr, maxEntities);
      this.unsafe[fieldName as keyof typeof Skin.schema] = typedArray as Skin['unsafe'][keyof Skin['unsafe']];
      memTracker.add(typedArray.byteLength);
    }

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this._cursor = {
      get entity(): number {
        return self._cursorIndex;
      },

      get skinId(): number {
        return self.unsafe.skinId[self._cursorIndex];
      },

      set skinId(value: number) {
        self.unsafe.skinId[self._cursorIndex] = value;
      },
    };
  }

  public static calculateSize(maxEntities: number, memTracker: MemoryTracker): void {
    for (const [, TypedArrayConstructor] of Object.entries(this.schema)) {
      memTracker.add(maxEntities * TypedArrayConstructor.BYTES_PER_ELEMENT);
    }
  }
}

Object.defineProperty(Skin, 'name', { value: 'Skin' });
