// Generated by @lagless/codegen. Do not edit manually.
import { AbstractFilter, IComponentConstructor } from '@lagless/core';
import { Transform2d } from './Transform2d.js';
import { Velocity2d } from './Velocity2d.js';
import { CircleBody } from './CircleBody.js';

export class SumoCharacterFilter extends AbstractFilter {
  public static readonly include: Array<IComponentConstructor> = [Transform2d, Velocity2d, CircleBody];
  public static readonly exclude: Array<IComponentConstructor> = [];

  public readonly includeMask: number = 7;
  public readonly excludeMask: number = 0;
}

Object.defineProperty(SumoCharacterFilter, 'name', { value: 'SumoCharacterFilter' });
