// Generated by @lagless/codegen. Do not edit manually.
import { AbstractFilter, IComponentConstructor } from '@lagless/core';
import { Velocity2d } from './Velocity2d.js';
import { Transform2d } from './Transform2d.js';

export class Velocity2dFilter extends AbstractFilter {
  public static readonly include: Array<IComponentConstructor> = [Velocity2d, Transform2d];
  public static readonly exclude: Array<IComponentConstructor> = [];

  public readonly includeMask: number = 6;
  public readonly excludeMask: number = 0;
}

Object.defineProperty(Velocity2dFilter, 'name', { value: 'Velocity2dFilter' });
