// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class AnimationState {
  public static readonly ID = 3;
  public static readonly schema = {
    animationId: Uint8Array,

    animationTime: Float32Array,

    animationSpeed: Float32Array,

    prevAnimationId: Uint8Array,

    transitionProgress: Float32Array,

    transitionDuration: Float32Array,

    locomotionAngle: Float32Array,

    locomotionSpeed: Float32Array,
  };

  public readonly unsafe = {} as {
    animationId: Uint8Array;

    animationTime: Float32Array;

    animationSpeed: Float32Array;

    prevAnimationId: Uint8Array;

    transitionProgress: Float32Array;

    transitionDuration: Float32Array;

    locomotionAngle: Float32Array;

    locomotionSpeed: Float32Array;
  };

  private _cursorIndex = 0;
  private readonly _cursor: {
    readonly entity: number;

    animationId: number;

    animationTime: number;

    animationSpeed: number;

    prevAnimationId: number;

    transitionProgress: number;

    transitionDuration: number;

    locomotionAngle: number;

    locomotionSpeed: number;
  };

  public getCursor(index: number) {
    this._cursorIndex = index;
    return this._cursor;
  }

  constructor(maxEntities: number, buffer: ArrayBuffer, memTracker: MemoryTracker) {
    this.unsafe.animationId = new Uint8Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.animationId.byteLength);

    this.unsafe.animationTime = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.animationTime.byteLength);

    this.unsafe.animationSpeed = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.animationSpeed.byteLength);

    this.unsafe.prevAnimationId = new Uint8Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.prevAnimationId.byteLength);

    this.unsafe.transitionProgress = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.transitionProgress.byteLength);

    this.unsafe.transitionDuration = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.transitionDuration.byteLength);

    this.unsafe.locomotionAngle = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.locomotionAngle.byteLength);

    this.unsafe.locomotionSpeed = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.locomotionSpeed.byteLength);

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this._cursor = {
      get entity(): number {
        return self._cursorIndex;
      },

      get animationId(): number {
        return self.unsafe.animationId[self._cursorIndex];
      },

      set animationId(value: number) {
        self.unsafe.animationId[self._cursorIndex] = value;
      },

      get animationTime(): number {
        return self.unsafe.animationTime[self._cursorIndex];
      },

      set animationTime(value: number) {
        self.unsafe.animationTime[self._cursorIndex] = value;
      },

      get animationSpeed(): number {
        return self.unsafe.animationSpeed[self._cursorIndex];
      },

      set animationSpeed(value: number) {
        self.unsafe.animationSpeed[self._cursorIndex] = value;
      },

      get prevAnimationId(): number {
        return self.unsafe.prevAnimationId[self._cursorIndex];
      },

      set prevAnimationId(value: number) {
        self.unsafe.prevAnimationId[self._cursorIndex] = value;
      },

      get transitionProgress(): number {
        return self.unsafe.transitionProgress[self._cursorIndex];
      },

      set transitionProgress(value: number) {
        self.unsafe.transitionProgress[self._cursorIndex] = value;
      },

      get transitionDuration(): number {
        return self.unsafe.transitionDuration[self._cursorIndex];
      },

      set transitionDuration(value: number) {
        self.unsafe.transitionDuration[self._cursorIndex] = value;
      },

      get locomotionAngle(): number {
        return self.unsafe.locomotionAngle[self._cursorIndex];
      },

      set locomotionAngle(value: number) {
        self.unsafe.locomotionAngle[self._cursorIndex] = value;
      },

      get locomotionSpeed(): number {
        return self.unsafe.locomotionSpeed[self._cursorIndex];
      },

      set locomotionSpeed(value: number) {
        self.unsafe.locomotionSpeed[self._cursorIndex] = value;
      },
    };
  }

  public static calculateSize(maxEntities: number, memTracker: MemoryTracker): void {
    for (const [, TypedArrayConstructor] of Object.entries(this.schema)) {
      memTracker.add(maxEntities * TypedArrayConstructor.BYTES_PER_ELEMENT);
    }
  }
}

Object.defineProperty(AnimationState, 'name', { value: 'AnimationState' });
