// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class CharacterState {
  public static readonly ID = 2;
  public static readonly schema = {
    verticalVelocity: Float32Array,

    grounded: Uint8Array,

    currentSpeed: Float32Array,

    jumpCount: Uint8Array,

    moveInputX: Float32Array,

    moveInputZ: Float32Array,

    isSprinting: Uint8Array,

    facingYaw: Float32Array,

    locomotionAngle: Float32Array,
  };

  public readonly unsafe = {} as {
    verticalVelocity: Float32Array;

    grounded: Uint8Array;

    currentSpeed: Float32Array;

    jumpCount: Uint8Array;

    moveInputX: Float32Array;

    moveInputZ: Float32Array;

    isSprinting: Uint8Array;

    facingYaw: Float32Array;

    locomotionAngle: Float32Array;
  };

  private _cursorIndex = 0;
  private readonly _cursor: {
    readonly entity: number;

    verticalVelocity: number;

    grounded: number;

    currentSpeed: number;

    jumpCount: number;

    moveInputX: number;

    moveInputZ: number;

    isSprinting: number;

    facingYaw: number;

    locomotionAngle: number;
  };

  public getCursor(index: number) {
    this._cursorIndex = index;
    return this._cursor;
  }

  constructor(maxEntities: number, buffer: ArrayBuffer, memTracker: MemoryTracker) {
    this.unsafe.verticalVelocity = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.verticalVelocity.byteLength);

    this.unsafe.grounded = new Uint8Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.grounded.byteLength);

    this.unsafe.currentSpeed = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.currentSpeed.byteLength);

    this.unsafe.jumpCount = new Uint8Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.jumpCount.byteLength);

    this.unsafe.moveInputX = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.moveInputX.byteLength);

    this.unsafe.moveInputZ = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.moveInputZ.byteLength);

    this.unsafe.isSprinting = new Uint8Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.isSprinting.byteLength);

    this.unsafe.facingYaw = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.facingYaw.byteLength);

    this.unsafe.locomotionAngle = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.locomotionAngle.byteLength);

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this._cursor = {
      get entity(): number {
        return self._cursorIndex;
      },

      get verticalVelocity(): number {
        return self.unsafe.verticalVelocity[self._cursorIndex];
      },

      set verticalVelocity(value: number) {
        self.unsafe.verticalVelocity[self._cursorIndex] = value;
      },

      get grounded(): number {
        return self.unsafe.grounded[self._cursorIndex];
      },

      set grounded(value: number) {
        self.unsafe.grounded[self._cursorIndex] = value;
      },

      get currentSpeed(): number {
        return self.unsafe.currentSpeed[self._cursorIndex];
      },

      set currentSpeed(value: number) {
        self.unsafe.currentSpeed[self._cursorIndex] = value;
      },

      get jumpCount(): number {
        return self.unsafe.jumpCount[self._cursorIndex];
      },

      set jumpCount(value: number) {
        self.unsafe.jumpCount[self._cursorIndex] = value;
      },

      get moveInputX(): number {
        return self.unsafe.moveInputX[self._cursorIndex];
      },

      set moveInputX(value: number) {
        self.unsafe.moveInputX[self._cursorIndex] = value;
      },

      get moveInputZ(): number {
        return self.unsafe.moveInputZ[self._cursorIndex];
      },

      set moveInputZ(value: number) {
        self.unsafe.moveInputZ[self._cursorIndex] = value;
      },

      get isSprinting(): number {
        return self.unsafe.isSprinting[self._cursorIndex];
      },

      set isSprinting(value: number) {
        self.unsafe.isSprinting[self._cursorIndex] = value;
      },

      get facingYaw(): number {
        return self.unsafe.facingYaw[self._cursorIndex];
      },

      set facingYaw(value: number) {
        self.unsafe.facingYaw[self._cursorIndex] = value;
      },

      get locomotionAngle(): number {
        return self.unsafe.locomotionAngle[self._cursorIndex];
      },

      set locomotionAngle(value: number) {
        self.unsafe.locomotionAngle[self._cursorIndex] = value;
      },
    };
  }

  public static calculateSize(maxEntities: number, memTracker: MemoryTracker): void {
    for (const [, TypedArrayConstructor] of Object.entries(this.schema)) {
      memTracker.add(maxEntities * TypedArrayConstructor.BYTES_PER_ELEMENT);
    }
  }
}

Object.defineProperty(CharacterState, 'name', { value: 'CharacterState' });
