// Generated by @lagless/codegen. Do not edit manually.
import { FieldType } from '@lagless/binary';

export class CharacterMove {
  public static readonly id = 3;
  public readonly id = 3;

  // 4 + 4 + 4 + 1 + 1 = 14;
  public readonly byteLength = 14;

  public readonly fields = [
    { name: 'directionX', type: FieldType.Float32, isArray: false, byteLength: 4 },

    { name: 'directionZ', type: FieldType.Float32, isArray: false, byteLength: 4 },

    { name: 'cameraYaw', type: FieldType.Float32, isArray: false, byteLength: 4 },

    { name: 'jump', type: FieldType.Uint8, isArray: false, byteLength: 1 },

    { name: 'sprint', type: FieldType.Uint8, isArray: false, byteLength: 1 },
  ] as const;

  public readonly schema!: {
    directionX: number;

    directionZ: number;

    cameraYaw: number;

    jump: number;

    sprint: number;
  };
}
