// Generated by @lagless/codegen. Do not edit manually.
import { AbstractFilter, IComponentConstructor } from '@lagless/core';
import { Transform3d } from './Transform3d.js';
import { PhysicsRefs } from './PhysicsRefs.js';
import { CharacterState } from './CharacterState.js';
import { AnimationState } from './AnimationState.js';
import { PlayerTag } from './PlayerTag.js';

export class CharacterFilter extends AbstractFilter {
  public static readonly include: Array<IComponentConstructor> = [
    Transform3d,
    PhysicsRefs,
    CharacterState,
    AnimationState,
    PlayerTag,
  ];
  public static readonly exclude: Array<IComponentConstructor> = [];

  public readonly includeMask: number[] = [31];
  public readonly excludeMask: number[] = [0];
}

Object.defineProperty(CharacterFilter, 'name', { value: 'CharacterFilter' });
