// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class GameState {
  public static readonly schema = {
    gamePhase: Uint8Array,

    sceneInitialized: Uint8Array,
  };

  public readonly unsafe = {} as {
    gamePhase: Uint8Array;

    sceneInitialized: Uint8Array;
  };

  public readonly safe: {
    gamePhase: number;

    sceneInitialized: number;
  };

  constructor(buffer: ArrayBuffer, memTracker: MemoryTracker) {
    // gamePhase
    this.unsafe['gamePhase'] = new Uint8Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);

    // sceneInitialized
    this.unsafe['sceneInitialized'] = new Uint8Array(buffer, memTracker.ptr, 1);
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this.safe = {
      get gamePhase() {
        return self.unsafe['gamePhase'][0];
      },
      set gamePhase(value: number) {
        self.unsafe['gamePhase'][0] = value;
      },

      get sceneInitialized() {
        return self.unsafe['sceneInitialized'][0];
      },
      set sceneInitialized(value: number) {
        self.unsafe['sceneInitialized'][0] = value;
      },
    };
  }

  public static calculateSize(memTracker: MemoryTracker): void {
    // gamePhase
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);

    // sceneInitialized
    memTracker.add(Uint8Array.BYTES_PER_ELEMENT * 1);
  }
}

Object.defineProperty(GameState, 'name', { value: 'GameState' });
