// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class PhysicsRefs {
  public static readonly ID = 1;
  public static readonly schema = {
    bodyHandle: Float64Array,

    colliderHandle: Float64Array,

    bodyType: Uint8Array,

    collisionLayer: Uint16Array,
  };

  public readonly unsafe = {} as {
    bodyHandle: Float64Array;

    colliderHandle: Float64Array;

    bodyType: Uint8Array;

    collisionLayer: Uint16Array;
  };

  private _cursorIndex = 0;
  private readonly _cursor: {
    readonly entity: number;

    bodyHandle: number;

    colliderHandle: number;

    bodyType: number;

    collisionLayer: number;
  };

  public getCursor(index: number) {
    this._cursorIndex = index;
    return this._cursor;
  }

  constructor(maxEntities: number, buffer: ArrayBuffer, memTracker: MemoryTracker) {
    this.unsafe.bodyHandle = new Float64Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.bodyHandle.byteLength);

    this.unsafe.colliderHandle = new Float64Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.colliderHandle.byteLength);

    this.unsafe.bodyType = new Uint8Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.bodyType.byteLength);

    this.unsafe.collisionLayer = new Uint16Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.collisionLayer.byteLength);

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this._cursor = {
      get entity(): number {
        return self._cursorIndex;
      },

      get bodyHandle(): number {
        return self.unsafe.bodyHandle[self._cursorIndex];
      },

      set bodyHandle(value: number) {
        self.unsafe.bodyHandle[self._cursorIndex] = value;
      },

      get colliderHandle(): number {
        return self.unsafe.colliderHandle[self._cursorIndex];
      },

      set colliderHandle(value: number) {
        self.unsafe.colliderHandle[self._cursorIndex] = value;
      },

      get bodyType(): number {
        return self.unsafe.bodyType[self._cursorIndex];
      },

      set bodyType(value: number) {
        self.unsafe.bodyType[self._cursorIndex] = value;
      },

      get collisionLayer(): number {
        return self.unsafe.collisionLayer[self._cursorIndex];
      },

      set collisionLayer(value: number) {
        self.unsafe.collisionLayer[self._cursorIndex] = value;
      },
    };
  }

  public static calculateSize(maxEntities: number, memTracker: MemoryTracker): void {
    for (const [, TypedArrayConstructor] of Object.entries(this.schema)) {
      memTracker.add(maxEntities * TypedArrayConstructor.BYTES_PER_ELEMENT);
    }
  }
}

Object.defineProperty(PhysicsRefs, 'name', { value: 'PhysicsRefs' });
