// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class PlayerTag {
  public static readonly ID = 4;
  public static readonly IS_TAG = true;
  public static readonly schema = {};

  public readonly unsafe = {} as Record<string, never>;

  constructor(_maxEntities: number, _buffer: ArrayBuffer, _memTracker: MemoryTracker) {}

  public static calculateSize(_maxEntities: number, _memTracker: MemoryTracker): void {}
}

Object.defineProperty(PlayerTag, 'name', { value: 'PlayerTag' });
