// Generated by @lagless/codegen. Do not edit manually.
import { FieldType } from '@lagless/binary';

export class PlayerJoined {
  public static readonly id = 1;
  public readonly id = 1;

  // 1 + 16 = 17;
  public readonly byteLength = 17;

  public readonly fields = [
    { name: 'slot', type: FieldType.Uint8, isArray: false, byteLength: 1 },

    { name: 'playerId', type: FieldType.Uint8, isArray: true, arrayLength: 16, byteLength: 16 },
  ] as const;

  public readonly schema!: {
    slot: number;

    playerId: Uint8Array;
  };
}
