// Generated by @lagless/codegen. Do not edit manually.
import { FieldType } from '@lagless/binary';

export class ReportHash {
  public static readonly id = 4;
  public readonly id = 4;

  // 4 + 4 = 8;
  public readonly byteLength = 8;

  public readonly fields = [
    { name: 'hash', type: FieldType.Uint32, isArray: false, byteLength: 4 },

    { name: 'atTick', type: FieldType.Uint32, isArray: false, byteLength: 4 },
  ] as const;

  public readonly schema!: {
    hash: number;

    atTick: number;
  };
}
