// Generated by @lagless/codegen. Do not edit manually.
import { InputRegistry } from '@lagless/core';

import { PlayerJoined } from './PlayerJoined.js';
import { PlayerLeft } from './PlayerLeft.js';
import { CharacterMove } from './CharacterMove.js';

export const RobloxLikeInputRegistry = new InputRegistry([PlayerJoined, PlayerLeft, CharacterMove]);
