// Generated by @lagless/codegen. Do not edit manually.
import { ECSDeps } from '@lagless/core';

import { Transform3d } from './Transform3d.js';
import { PhysicsRefs } from './PhysicsRefs.js';
import { CharacterState } from './CharacterState.js';
import { AnimationState } from './AnimationState.js';
import { PlayerTag } from './PlayerTag.js';
import { StaticObstacle } from './StaticObstacle.js';
import { GameState } from './GameState.js';
import { PlayerResource } from './PlayerResource.js';
import { CharacterFilter } from './CharacterFilter.js';
import { StaticObstacleFilter } from './StaticObstacleFilter.js';
import { PhysicsRefsFilter } from './PhysicsRefsFilter.js';
import { PlayerJoined } from './PlayerJoined.js';
import { PlayerLeft } from './PlayerLeft.js';
import { CharacterMove } from './CharacterMove.js';
import { ReportHash } from './ReportHash.js';

export const RobloxLikeCore: ECSDeps = {
  components: [Transform3d, PhysicsRefs, CharacterState, AnimationState, PlayerTag, StaticObstacle],
  singletons: [GameState],
  playerResources: [PlayerResource],
  filters: [CharacterFilter, StaticObstacleFilter, PhysicsRefsFilter],
  inputs: [PlayerJoined, PlayerLeft, CharacterMove, ReportHash],
};
