// Generated by @lagless/codegen. Do not edit manually.
import { AbstractInputProvider, ECSConfig } from '@lagless/core';
import { IECSSystemConstructor, ISignalConstructor } from '@lagless/core';
import { PhysicsRunner3d, PhysicsConfig3d, RapierModule3d } from '@lagless/physics3d';
import { CollisionLayers } from '@lagless/physics-shared';

import { RobloxLikeCore } from './RobloxLike.core.js';

export class RobloxLikeRunner extends PhysicsRunner3d {
  constructor(
    Config: ECSConfig,
    InputProviderInstance: AbstractInputProvider,
    Systems: Array<IECSSystemConstructor>,
    Signals: Array<ISignalConstructor> = [],
    rapier: RapierModule3d,
    physicsConfig?: PhysicsConfig3d,
    collisionLayers?: CollisionLayers,
    extraRegistrations?: Array<[unknown, unknown]>,
  ) {
    super(Config, InputProviderInstance, Systems, Signals, RobloxLikeCore, rapier, physicsConfig, collisionLayers, extraRegistrations);
  }
}
