// Generated by @lagless/codegen. Do not edit manually.
import { AbstractFilter, IComponentConstructor } from '@lagless/core';
import { Transform3d } from './Transform3d.js';
import { PhysicsRefs } from './PhysicsRefs.js';
import { StaticObstacle } from './StaticObstacle.js';

export class StaticObstacleFilter extends AbstractFilter {
  public static readonly include: Array<IComponentConstructor> = [Transform3d, PhysicsRefs, StaticObstacle];
  public static readonly exclude: Array<IComponentConstructor> = [];

  public readonly includeMask: number[] = [35];
  public readonly excludeMask: number[] = [0];
}

Object.defineProperty(StaticObstacleFilter, 'name', { value: 'StaticObstacleFilter' });
