// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class Transform3d {
  public static readonly ID = 0;
  public static readonly schema = {
    positionX: Float32Array,

    positionY: Float32Array,

    positionZ: Float32Array,

    rotationX: Float32Array,

    rotationY: Float32Array,

    rotationZ: Float32Array,

    rotationW: Float32Array,

    prevPositionX: Float32Array,

    prevPositionY: Float32Array,

    prevPositionZ: Float32Array,

    prevRotationX: Float32Array,

    prevRotationY: Float32Array,

    prevRotationZ: Float32Array,

    prevRotationW: Float32Array,
  };

  public readonly unsafe = {} as {
    positionX: Float32Array;

    positionY: Float32Array;

    positionZ: Float32Array;

    rotationX: Float32Array;

    rotationY: Float32Array;

    rotationZ: Float32Array;

    rotationW: Float32Array;

    prevPositionX: Float32Array;

    prevPositionY: Float32Array;

    prevPositionZ: Float32Array;

    prevRotationX: Float32Array;

    prevRotationY: Float32Array;

    prevRotationZ: Float32Array;

    prevRotationW: Float32Array;
  };

  private _cursorIndex = 0;
  private readonly _cursor: {
    readonly entity: number;

    positionX: number;

    positionY: number;

    positionZ: number;

    rotationX: number;

    rotationY: number;

    rotationZ: number;

    rotationW: number;

    prevPositionX: number;

    prevPositionY: number;

    prevPositionZ: number;

    prevRotationX: number;

    prevRotationY: number;

    prevRotationZ: number;

    prevRotationW: number;
  };

  public getCursor(index: number) {
    this._cursorIndex = index;
    return this._cursor;
  }

  constructor(maxEntities: number, buffer: ArrayBuffer, memTracker: MemoryTracker) {
    this.unsafe.positionX = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.positionX.byteLength);

    this.unsafe.positionY = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.positionY.byteLength);

    this.unsafe.positionZ = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.positionZ.byteLength);

    this.unsafe.rotationX = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.rotationX.byteLength);

    this.unsafe.rotationY = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.rotationY.byteLength);

    this.unsafe.rotationZ = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.rotationZ.byteLength);

    this.unsafe.rotationW = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.rotationW.byteLength);

    this.unsafe.prevPositionX = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.prevPositionX.byteLength);

    this.unsafe.prevPositionY = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.prevPositionY.byteLength);

    this.unsafe.prevPositionZ = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.prevPositionZ.byteLength);

    this.unsafe.prevRotationX = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.prevRotationX.byteLength);

    this.unsafe.prevRotationY = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.prevRotationY.byteLength);

    this.unsafe.prevRotationZ = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.prevRotationZ.byteLength);

    this.unsafe.prevRotationW = new Float32Array(buffer, memTracker.ptr, maxEntities);
    memTracker.add(this.unsafe.prevRotationW.byteLength);

    // eslint-disable-next-line @typescript-eslint/no-this-alias
    const self = this;

    this._cursor = {
      get entity(): number {
        return self._cursorIndex;
      },

      get positionX(): number {
        return self.unsafe.positionX[self._cursorIndex];
      },

      set positionX(value: number) {
        self.unsafe.positionX[self._cursorIndex] = value;
      },

      get positionY(): number {
        return self.unsafe.positionY[self._cursorIndex];
      },

      set positionY(value: number) {
        self.unsafe.positionY[self._cursorIndex] = value;
      },

      get positionZ(): number {
        return self.unsafe.positionZ[self._cursorIndex];
      },

      set positionZ(value: number) {
        self.unsafe.positionZ[self._cursorIndex] = value;
      },

      get rotationX(): number {
        return self.unsafe.rotationX[self._cursorIndex];
      },

      set rotationX(value: number) {
        self.unsafe.rotationX[self._cursorIndex] = value;
      },

      get rotationY(): number {
        return self.unsafe.rotationY[self._cursorIndex];
      },

      set rotationY(value: number) {
        self.unsafe.rotationY[self._cursorIndex] = value;
      },

      get rotationZ(): number {
        return self.unsafe.rotationZ[self._cursorIndex];
      },

      set rotationZ(value: number) {
        self.unsafe.rotationZ[self._cursorIndex] = value;
      },

      get rotationW(): number {
        return self.unsafe.rotationW[self._cursorIndex];
      },

      set rotationW(value: number) {
        self.unsafe.rotationW[self._cursorIndex] = value;
      },

      get prevPositionX(): number {
        return self.unsafe.prevPositionX[self._cursorIndex];
      },

      set prevPositionX(value: number) {
        self.unsafe.prevPositionX[self._cursorIndex] = value;
      },

      get prevPositionY(): number {
        return self.unsafe.prevPositionY[self._cursorIndex];
      },

      set prevPositionY(value: number) {
        self.unsafe.prevPositionY[self._cursorIndex] = value;
      },

      get prevPositionZ(): number {
        return self.unsafe.prevPositionZ[self._cursorIndex];
      },

      set prevPositionZ(value: number) {
        self.unsafe.prevPositionZ[self._cursorIndex] = value;
      },

      get prevRotationX(): number {
        return self.unsafe.prevRotationX[self._cursorIndex];
      },

      set prevRotationX(value: number) {
        self.unsafe.prevRotationX[self._cursorIndex] = value;
      },

      get prevRotationY(): number {
        return self.unsafe.prevRotationY[self._cursorIndex];
      },

      set prevRotationY(value: number) {
        self.unsafe.prevRotationY[self._cursorIndex] = value;
      },

      get prevRotationZ(): number {
        return self.unsafe.prevRotationZ[self._cursorIndex];
      },

      set prevRotationZ(value: number) {
        self.unsafe.prevRotationZ[self._cursorIndex] = value;
      },

      get prevRotationW(): number {
        return self.unsafe.prevRotationW[self._cursorIndex];
      },

      set prevRotationW(value: number) {
        self.unsafe.prevRotationW[self._cursorIndex] = value;
      },
    };
  }

  public static calculateSize(maxEntities: number, memTracker: MemoryTracker): void {
    for (const [, TypedArrayConstructor] of Object.entries(this.schema)) {
      memTracker.add(maxEntities * TypedArrayConstructor.BYTES_PER_ELEMENT);
    }
  }
}

Object.defineProperty(Transform3d, 'name', { value: 'Transform3d' });
