// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class PlayerResource {
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-expect-error
  public static readonly name = 'PlayerResource';
  public static readonly schema = {
    health: Int32Array,

    mana: Int32Array,

    stamina: Int32Array,
  };

  public readonly unsafe = {} as {
    health: Int32Array;

    mana: Int32Array;

    stamina: Int32Array;
  };

  constructor(buffer: ArrayBuffer, memTracker: MemoryTracker) {
    // health
    this.unsafe['health'] = new Int32Array(buffer, memTracker.ptr, 1);
    memTracker.add(Int32Array.BYTES_PER_ELEMENT * 1);

    // mana
    this.unsafe['mana'] = new Int32Array(buffer, memTracker.ptr, 1);
    memTracker.add(Int32Array.BYTES_PER_ELEMENT * 1);

    // stamina
    this.unsafe['stamina'] = new Int32Array(buffer, memTracker.ptr, 1);
    memTracker.add(Int32Array.BYTES_PER_ELEMENT * 1);
  }

  public static calculateSize(memTracker: MemoryTracker): void {
    // health
    memTracker.add(Int32Array.BYTES_PER_ELEMENT * 1);

    // mana
    memTracker.add(Int32Array.BYTES_PER_ELEMENT * 1);

    // stamina
    memTracker.add(Int32Array.BYTES_PER_ELEMENT * 1);
  }
}
