// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class Projectile {
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-expect-error
  public static readonly name = 'Projectile';
  public static readonly ID = 2;
  public static readonly schema = {
    speed: Float32Array,

    directionX: Float32Array,

    directionY: Float32Array,
  };

  public readonly unsafe = {} as {
    speed: Float32Array;

    directionX: Float32Array;

    directionY: Float32Array;
  };

  constructor(maxEntities: number, buffer: ArrayBuffer, memTracker: MemoryTracker) {
    for (const [fieldName, TypedArrayConstructor] of Object.entries(Projectile.schema)) {
      const typedArray = new TypedArrayConstructor(buffer, memTracker.ptr, maxEntities);
      this.unsafe[fieldName as keyof typeof Projectile.schema] =
        typedArray as Projectile['unsafe'][keyof Projectile['unsafe']];
      memTracker.add(typedArray.byteLength);
    }
  }

  public static calculateSize(maxEntities: number, memTracker: MemoryTracker): void {
    for (const [, TypedArrayConstructor] of Object.entries(this.schema)) {
      memTracker.add(maxEntities * TypedArrayConstructor.BYTES_PER_ELEMENT);
    }
  }
}
