// Generated by @lagless/codegen. Do not edit manually.
import { ECSDeps } from '@lagless/core';

import { Transform2d } from './Transform2d.js';
import { Projectile } from './Projectile.js';
import { GameState } from './GameState.js';
import { PlayerResource } from './PlayerResource.js';
import { MovingProjectiles } from './MovingProjectiles.js';

export const ToolsCore: ECSDeps = {
  components: [Transform2d, Projectile],
  singletons: [GameState],
  playerResources: [PlayerResource],
  filters: [MovingProjectiles],
  inputs: [],
};
