export * from './lib/types/index.js';
export { GeneratedMap } from './lib/core/generated-map.js';
export { MapGenerator } from './lib/core/map-generator.js';
export { computeDimensions } from './lib/core/map-dimensions.js';
export { generateJaggedAabbPoints } from './lib/math/jagged-aabb.js';
export { pointInPolygon, polygonArea, distToSegmentSq, computePolygonBounds } from './lib/math/polygon-utils.js';
export { testCircleCircle, testCircleAabb, testAabbAabb } from './lib/math/collision-test.js';
export { BiomeFeature } from './lib/features/biome-feature.js';
export { ShoreFeature } from './lib/features/shore-feature.js';
export { GrassFeature } from './lib/features/grass-feature.js';
export { SpatialGridCollisionProvider } from './lib/collision/spatial-grid-provider.js';
export { catmullRom, catmullRomDerivative, getControlPoints } from './lib/math/catmull-rom.js';
export { Spline } from './lib/math/spline.js';
export { generateRiverPolygon } from './lib/math/river-polygon.js';
export { RiverFeature } from './lib/features/river-feature.js';
export { LakeFeature } from './lib/features/lake-feature.js';
export { TerrainQuery } from './lib/core/terrain-query.js';
export type { TerrainQueryInputs } from './lib/core/terrain-query.js';
export { ObjectPlacementFeature } from './lib/features/object-placement-feature.js';
export { GroundPatchFeature } from './lib/features/ground-patch-feature.js';
export { BridgeFeature } from './lib/features/bridge-feature.js';
export { RapierCollisionProvider } from './lib/collision/rapier-provider.js';
export { PlacesFeature } from './lib/features/places-feature.js';
export { STANDARD_BIOME } from './lib/presets/standard-biome.js';
export { createMapColliders } from './lib/physics/create-map-colliders.js';
export type { MapPhysicsProvider, CreateMapCollidersOptions } from './lib/physics/create-map-colliders.js';
export { CANOPY_SENSOR_TAG } from './lib/physics/canopy-sensor-tag.js';
export { sortPlacedObjects } from './lib/utils/sort-placed-objects.js';
export { extractCanopyZones, isInsideCanopyZone } from './lib/utils/extract-canopy-zones.js';
export type { CanopyZone, CanopyZoneCircle, CanopyZoneCuboid } from './lib/utils/extract-canopy-zones.js';
