// Generated by @lagless/codegen. Do not edit manually.
import { AbstractInputProvider, ECSConfig, ECSRunner } from '@lagless/core';
import { IECSSystemConstructor, ISignalConstructor } from '@lagless/core';

import { <%= projectName %>Core } from './<%= projectName %>.core.js';

export class <%= projectName %>Runner extends ECSRunner {
  constructor(
    Config: ECSConfig,
    InputProviderInstance: AbstractInputProvider,
    Systems: Array<IECSSystemConstructor>,
    Signals: Array<ISignalConstructor> = []
  ) {
    super(Config, InputProviderInstance, Systems, Signals, <%= projectName %>Core);
  }
}
