// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class GameState {
  public static readonly schema = {
    gamePhase: Uint8Array,
  };

  public readonly safe = {} as {
    gamePhase: number;
  };

  constructor(buffer: ArrayBuffer, memTracker: MemoryTracker) {
    const gamePhaseArray = new Uint8Array(buffer, memTracker.ptr, 1);
    memTracker.add(1);

    Object.defineProperty(this.safe, 'gamePhase', {
      get: () => gamePhaseArray[0],
      set: (v: number) => { gamePhaseArray[0] = v; },
      enumerable: true,
    });
  }

  public static calculateSize(_maxEntities: number, memTracker: MemoryTracker): void {
    memTracker.add(1);
  }
}

Object.defineProperty(GameState, 'name', { value: 'GameState' });
