// Generated by @lagless/codegen. Do not edit manually.
import { InputPayloadBuffer } from '@lagless/core';

export class MoveInput {
  public static readonly id = 2;
  public static readonly byteLength = 8;

  public readonly schema!: {
    directionX: number;
    directionY: number;
  };

  public static encode(data: MoveInput['schema'], buffer: InputPayloadBuffer): void {
    buffer.writeFloat32(data.directionX);
    buffer.writeFloat32(data.directionY);
  }

  public static decode(buffer: InputPayloadBuffer): MoveInput['schema'] {
    const directionX = buffer.readFloat32();
    const directionY = buffer.readFloat32();
    return { directionX, directionY };
  }
}
