// Generated by @lagless/codegen. Do not edit manually.
import { AbstractFilter, MemoryTracker } from '@lagless/binary';
import { Transform2d } from './Transform2d.js';
import { Velocity2d } from './Velocity2d.js';

export class MovingFilter extends AbstractFilter {
  public static readonly includeMask = Transform2d.ID | Velocity2d.ID;
  public static readonly excludeMask = 0;

  constructor(maxEntities: number, buffer: ArrayBuffer, memTracker: MemoryTracker) {
    super(maxEntities, Transform2d.ID | Velocity2d.ID, 0, buffer, memTracker);
  }
}

Object.defineProperty(MovingFilter, 'name', { value: 'MovingFilter' });
