// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/binary';

export class PlayerResource {
  public static readonly schema = {
    id: { type: Uint8Array, length: 16 },
    entity: Uint32Array,
    connected: Uint8Array,
    lastReportedHash: Uint32Array,
    lastReportedHashTick: Uint32Array,
    hashMismatchCount: Uint16Array,
  };

  public readonly safe = {} as {
    entity: number;
    connected: number;
    lastReportedHash: number;
    lastReportedHashTick: number;
    hashMismatchCount: number;
  };

  public readonly unsafe = {} as {
    id: Uint8Array;
  };

  constructor(playerIndex: number, buffer: ArrayBuffer, memTracker: MemoryTracker) {
    // id: uint8[16]
    const idArray = new Uint8Array(buffer, memTracker.ptr, 16);
    memTracker.add(16);
    (this.unsafe as Record<string, unknown>).id = idArray;

    // entity: uint32
    const entityArray = new Uint32Array(buffer, memTracker.ptr, 1);
    memTracker.add(4);
    Object.defineProperty(this.safe, 'entity', {
      get: () => entityArray[0],
      set: (v: number) => { entityArray[0] = v; },
      enumerable: true,
    });

    // connected: uint8
    const connectedArray = new Uint8Array(buffer, memTracker.ptr, 1);
    memTracker.add(1);
    Object.defineProperty(this.safe, 'connected', {
      get: () => connectedArray[0],
      set: (v: number) => { connectedArray[0] = v; },
      enumerable: true,
    });

    // lastReportedHash: uint32
    const lastReportedHashArray = new Uint32Array(buffer, memTracker.ptr, 1);
    memTracker.add(4);
    Object.defineProperty(this.safe, 'lastReportedHash', {
      get: () => lastReportedHashArray[0],
      set: (v: number) => { lastReportedHashArray[0] = v; },
      enumerable: true,
    });

    // lastReportedHashTick: uint32
    const lastReportedHashTickArray = new Uint32Array(buffer, memTracker.ptr, 1);
    memTracker.add(4);
    Object.defineProperty(this.safe, 'lastReportedHashTick', {
      get: () => lastReportedHashTickArray[0],
      set: (v: number) => { lastReportedHashTickArray[0] = v; },
      enumerable: true,
    });

    // hashMismatchCount: uint16
    const hashMismatchCountArray = new Uint16Array(buffer, memTracker.ptr, 1);
    memTracker.add(2);
    Object.defineProperty(this.safe, 'hashMismatchCount', {
      get: () => hashMismatchCountArray[0],
      set: (v: number) => { hashMismatchCountArray[0] = v; },
      enumerable: true,
    });
  }

  public static calculateSize(_maxEntities: number, memTracker: MemoryTracker): void {
    memTracker.add(16 + 4 + 1 + 4 + 4 + 2);
  }
}

Object.defineProperty(PlayerResource, 'name', { value: 'PlayerResource' });
