// Generated by @lagless/codegen. Do not edit manually.
import { InputDef, InputByteLength, InputPayloadBuffer } from '@lagless/core';

export class PlayerJoined {
  public static readonly id = 0;
  public static readonly byteLength = 17;

  public readonly schema!: {
    slot: number;
    playerId: Uint8Array;
  };

  public static encode(data: PlayerJoined['schema'], buffer: InputPayloadBuffer): void {
    buffer.writeUint8(data.slot);
    for (let i = 0; i < 16; i++) buffer.writeUint8(data.playerId[i]);
  }

  public static decode(buffer: InputPayloadBuffer): PlayerJoined['schema'] {
    const slot = buffer.readUint8();
    const playerId = new Uint8Array(16);
    for (let i = 0; i < 16; i++) playerId[i] = buffer.readUint8();
    return { slot, playerId };
  }
}
