// Generated by @lagless/codegen. Do not edit manually.
import { AbstractFilter, MemoryTracker } from '@lagless/binary';
import { Transform2d } from './Transform2d.js';
import { PlayerBody } from './PlayerBody.js';

export class PlayerFilter extends AbstractFilter {
  public static readonly includeMask = Transform2d.ID | PlayerBody.ID;
  public static readonly excludeMask = 0;

  constructor(maxEntities: number, buffer: ArrayBuffer, memTracker: MemoryTracker) {
    super(maxEntities, Transform2d.ID | PlayerBody.ID, 0, buffer, memTracker);
  }
}

Object.defineProperty(PlayerFilter, 'name', { value: 'PlayerFilter' });
