// Generated by @lagless/codegen. Do not edit manually.
import { InputPayloadBuffer } from '@lagless/core';

export class PlayerLeft {
  public static readonly id = 1;
  public static readonly byteLength = 2;

  public readonly schema!: {
    slot: number;
    reason: number;
  };

  public static encode(data: PlayerLeft['schema'], buffer: InputPayloadBuffer): void {
    buffer.writeUint8(data.slot);
    buffer.writeUint8(data.reason);
  }

  public static decode(buffer: InputPayloadBuffer): PlayerLeft['schema'] {
    const slot = buffer.readUint8();
    const reason = buffer.readUint8();
    return { slot, reason };
  }
}
