// Generated by @lagless/codegen. Do not edit manually.
import { InputPayloadBuffer } from '@lagless/core';

export class ReportHash {
  public static readonly id = 3;
  public static readonly byteLength = 8;

  public readonly schema!: {
    hash: number;
    atTick: number;
  };

  public static encode(data: ReportHash['schema'], buffer: InputPayloadBuffer): void {
    buffer.writeUint32(data.hash);
    buffer.writeUint32(data.atTick);
  }

  public static decode(buffer: InputPayloadBuffer): ReportHash['schema'] {
    const hash = buffer.readUint32();
    const atTick = buffer.readUint32();
    return { hash, atTick };
  }
}
