// Generated by @lagless/codegen. Do not edit manually.
import { ECSDeps } from '@lagless/core';

import { Transform2d } from './Transform2d.js';
import { GameState } from './GameState.js';
import { PlayerResource } from './PlayerResource.js';
import { Transform2dFilter } from './Transform2dFilter.js';
import { PlayerJoined } from './PlayerJoined.js';
import { PlayerLeft } from './PlayerLeft.js';
import { Move } from './Move.js';

export const CircleSumoCore: ECSDeps = {
  components: [Transform2d],
  singletons: [GameState],
  playerResources: [PlayerResource],
  filters: [Transform2dFilter],
  inputs: [PlayerJoined, PlayerLeft, Move],
};
