// Generated by @lagless/codegen. Do not edit manually.
import { AbstractFilter, IComponentConstructor } from '@lagless/core';
import { Transform2d } from './Transform2d.js';

export class Transform2dFilter extends AbstractFilter {
  public static readonly include: Array<IComponentConstructor> = [Transform2d];
  public static readonly exclude: Array<IComponentConstructor> = [];

  public readonly includeMask: number = 1;
  public readonly excludeMask: number = 0;
}

Object.defineProperty(Transform2dFilter, 'name', { value: 'Transform2dFilter' });
