// Generated by @lagless/codegen. Do not edit manually.
import { ECSDeps } from '@lagless/types';

import { PhysicsRefs } from './PhysicsRefs.js';

export const Physics2dECSCore: ECSDeps = {
  components: [PhysicsRefs],
  singletons: [],
  playerResources: [],
  filters: [],
  inputs: [],
};
