// Generated by @lagless/codegen. Do not edit manually.
import { AbstractInputProvider, ECSConfig, ECSRunner } from '@lagless/core';
import { IECSSystemConstructor } from '@lagless/types';

import { Physics2dECSCore } from './ECSCore.js';

export class Physics2dRunner extends ECSRunner {
  constructor(Config: ECSConfig, InputProviderInstance: AbstractInputProvider, Systems: Array<IECSSystemConstructor>) {
    super(Config, InputProviderInstance, Systems, Physics2dECSCore);
  }
}
