// Generated by @lagless/codegen. Do not edit manually.
import { ECSDeps } from '@lagless/types';

import { Position } from './Position.js';
import { Velocity } from './Velocity.js';
import { Player } from './Player.js';
import { WorldSettings } from './WorldSettings.js';
import { PlayerResource } from './PlayerResource.js';
import { TestOnlyPositionFilter } from './TestOnlyPositionFilter.js';
import { TestOnlyVelocityFilter } from './TestOnlyVelocityFilter.js';
import { TestPositionAndVelocityFilter } from './TestPositionAndVelocityFilter.js';
import { PositionFilter } from './PositionFilter.js';
import { MovableFilter } from './MovableFilter.js';
import { StaticFilter } from './StaticFilter.js';
import { Move } from './Move.js';
import { MultipleMove } from './MultipleMove.js';

export const TestbedSimulationECSCore: ECSDeps = {
  components: [Position, Velocity, Player],
  singletons: [WorldSettings],
  playerResources: [PlayerResource],
  filters: [
    TestOnlyPositionFilter,
    TestOnlyVelocityFilter,
    TestPositionAndVelocityFilter,
    PositionFilter,
    MovableFilter,
    StaticFilter,
  ],
  inputs: [Move, MultipleMove],
};
