// Generated by @lagless/codegen. Do not edit manually.
import { AbstractFilter, IComponentConstructor } from '@lagless/types';
import { Position } from './Position.js';
import { Velocity } from './Velocity.js';

export class MovableFilter extends AbstractFilter {
  public static override readonly name = 'MovableFilter';
  public static readonly include: Array<IComponentConstructor> = [
    Position,
    Velocity,
  ];
  public static readonly exclude: Array<IComponentConstructor> = [];

  public readonly includeMask: number = 3;
  public readonly excludeMask: number = 0;
}
