// Generated by @lagless/codegen. Do not edit manually.
import { FieldType } from '@lagless/types';

export class Move {
  public static readonly id = 1;
  public readonly id = 1;

  // 8 + 8 = 16;
  public readonly byteLength = 16;

  public readonly fields = [
    { name: 'dx', type: FieldType.Float32, isArray: false, byteLength: 8 },

    { name: 'dy', type: FieldType.Float32, isArray: false, byteLength: 8 },
  ];

  public readonly schema!: {
    dx: number;

    dy: number;
  };
}
