// Generated by @lagless/codegen. Do not edit manually.
import { FieldType } from '@lagless/types';

export class MultipleMove {
  public static readonly id = 2;
  public readonly id = 2;

  // 8 + 8 + 128 + 8 = 152;
  public readonly byteLength = 152;

  public readonly fields = [
    { name: 'dx', type: FieldType.Float32, isArray: false, byteLength: 8 },

    { name: 'dy', type: FieldType.Float32, isArray: false, byteLength: 8 },

    {
      name: 'entities',
      type: FieldType.Uint32,
      isArray: true,
      arrayLength: 32,
      byteLength: 128,
    },

    {
      name: 'entitiesLength',
      type: FieldType.Uint8,
      isArray: false,
      byteLength: 8,
    },
  ];

  public readonly schema!: {
    dx: number;

    dy: number;

    entities: Uint32Array;

    entitiesLength: number;
  };
}
