// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/misc';

export class Position {
  public static readonly name = 'Position';
  public static readonly ID = 1;
  public static readonly schema = {
    x: Float32Array,

    y: Float32Array,
  };

  public readonly unsafe = {} as {
    x: Float32Array;

    y: Float32Array;
  };

  constructor(
    maxEntities: number,
    buffer: ArrayBuffer,
    memTracker: MemoryTracker
  ) {
    for (const [fieldName, TypedArrayConstructor] of Object.entries(
      Position.schema
    )) {
      const typedArray = new TypedArrayConstructor(
        buffer,
        memTracker.ptr,
        maxEntities
      );
      this.unsafe[fieldName as keyof typeof Position.schema] =
        typedArray as Position['unsafe'][keyof Position['unsafe']];
      memTracker.add(typedArray.byteLength);
    }
  }

  public static calculateSize(
    maxEntities: number,
    memTracker: MemoryTracker
  ): void {
    for (const [, TypedArrayConstructor] of Object.entries(this.schema)) {
      memTracker.add(maxEntities * TypedArrayConstructor.BYTES_PER_ELEMENT);
    }
  }
}
