// Generated by @lagless/codegen. Do not edit manually.
import { AbstractFilter, IComponentConstructor } from '@lagless/types';
import { Position } from './Position.js';

export class PositionFilter extends AbstractFilter {
  public static override readonly name = 'PositionFilter';
  public static readonly include: Array<IComponentConstructor> = [Position];
  public static readonly exclude: Array<IComponentConstructor> = [];

  public readonly includeMask: number = 1;
  public readonly excludeMask: number = 0;
}
