// Generated by @lagless/codegen. Do not edit manually.
import { AbstractFilter, IComponentConstructor } from '@lagless/types';
import { Position } from './Position.js';
import { Velocity } from './Velocity.js';

export class TestOnlyPositionFilter extends AbstractFilter {
  public static override readonly name = 'TestOnlyPositionFilter';
  public static readonly include: Array<IComponentConstructor> = [Position];
  public static readonly exclude: Array<IComponentConstructor> = [Velocity];

  public readonly includeMask: number = 1;
  public readonly excludeMask: number = 2;
}
