// Generated by @lagless/codegen. Do not edit manually.
import { AbstractFilter, IComponentConstructor } from '@lagless/types';
import { Velocity } from './Velocity.js';
import { Position } from './Position.js';

export class TestOnlyVelocityFilter extends AbstractFilter {
  public static override readonly name = 'TestOnlyVelocityFilter';
  public static readonly include: Array<IComponentConstructor> = [Velocity];
  public static readonly exclude: Array<IComponentConstructor> = [Position];

  public readonly includeMask: number = 2;
  public readonly excludeMask: number = 1;
}
