// Generated by @lagless/codegen. Do not edit manually.
import { InputRegistry } from '@lagless/core';

import { Move } from './Move.js';
import { MultipleMove } from './MultipleMove.js';

export const TestbedSimulationInputRegistry = new InputRegistry([
  Move,
  MultipleMove,
]);
