// Generated by @lagless/codegen. Do not edit manually.
import { AbstractInputProvider, ECSConfig, ECSRunner } from '@lagless/core';
import { IECSSystemConstructor } from '@lagless/types';

import { TestbedSimulationCore } from './TestbedSimulation.core.js';

export class TestbedSimulationRunner extends ECSRunner {
  constructor(
    Config: ECSConfig,
    InputProviderInstance: AbstractInputProvider,
    Systems: Array<IECSSystemConstructor>
  ) {
    super(Config, InputProviderInstance, Systems, TestbedSimulationCore);
  }
}
