// Generated by @lagless/codegen. Do not edit manually.
import { MemoryTracker } from '@lagless/misc';

export class Velocity {
  public static readonly name = 'Velocity';
  public static readonly ID = 2;
  public static readonly schema = {
    dx: Float32Array,

    dy: Float32Array,
  };

  public readonly unsafe = {} as {
    dx: Float32Array;

    dy: Float32Array;
  };

  constructor(
    maxEntities: number,
    buffer: ArrayBuffer,
    memTracker: MemoryTracker
  ) {
    for (const [fieldName, TypedArrayConstructor] of Object.entries(
      Velocity.schema
    )) {
      const typedArray = new TypedArrayConstructor(
        buffer,
        memTracker.ptr,
        maxEntities
      );
      this.unsafe[fieldName as keyof typeof Velocity.schema] =
        typedArray as Velocity['unsafe'][keyof Velocity['unsafe']];
      memTracker.add(typedArray.byteLength);
    }
  }

  public static calculateSize(
    maxEntities: number,
    memTracker: MemoryTracker
  ): void {
    for (const [, TypedArrayConstructor] of Object.entries(this.schema)) {
      memTracker.add(maxEntities * TypedArrayConstructor.BYTES_PER_ELEMENT);
    }
  }
}
